// Code generated by scripts/gen_commands/main.go DO NOT EDIT.
// Source: schema/internal-branch-restrictions-schema.yaml
//
// This file is regenerated whenever the schema changes in CI.
// Do not edit manually — run: go run scripts/gen_commands/main.go schema/internal-branch-restrictions-schema.yaml <output.go>

package commands

import (
	"context"
	"encoding/json"
	"fmt"
	"strconv"

	"github.com/spf13/cobra"

	"github.com/FabianSchurig/bitbucket-cli/internal/client"
	"github.com/FabianSchurig/bitbucket-cli/internal/handlers"
	"github.com/FabianSchurig/bitbucket-cli/internal/output"
)

// Ensure imports are used.
var (
	_ = context.Background
	_ = fmt.Errorf
	_ = json.Marshal
	_ = strconv.Itoa
	_ = client.NewClient
	_ = handlers.Dispatch
	_ = output.Format
)

// NewProjectBranchRestrictionsCommand returns the "project-branch-restrictions" cobra command with all sub-commands registered.
func NewProjectBranchRestrictionsCommand() *cobra.Command {
	cmd := &cobra.Command{
		Use:   "project-branch-restrictions",
		Short: `Manage Bitbucket project-level branch restrictions (internal API)`,
		Long: `Commands for listing and replacing branch restriction rules at the
*project* level via Bitbucket's internal API.

The Bitbucket public REST API (api.bitbucket.org/2.0) exposes branch
restrictions only at the *repository* level. Project-level restrictions
are configured in the web UI through an internal endpoint hosted at
https://bitbucket.org/!api/internal/. These commands wrap that endpoint
so the same configuration can be managed from the CLI, MCP, or Terraform.

Note: this is an undocumented internal API and is not covered by
Atlassian's public stability guarantees.

AUTHENTICATION (IMPORTANT):
The internal API does NOT accept HTTP Basic Auth (Atlassian API tokens,
workspace access tokens, or app passwords will all return 401). It only
accepts the same browser-style cookie auth the Bitbucket web UI sends.

To use these commands, set BOTH of the following environment variables
in addition to (or instead of) BITBUCKET_USERNAME / BITBUCKET_TOKEN:

  BITBUCKET_CSRF_TOKEN           value of the "csrftoken" browser cookie
  BITBUCKET_CLOUD_SESSION_TOKEN  value of the "cloud.session.token" cookie

You can grab both values from your browser's developer tools while
logged in to bitbucket.org (Application → Cookies → bitbucket.org).
The CLI / MCP server / Terraform provider will automatically detect that
the request URL contains "/!api/internal/" and switch from Basic Auth to
cookie auth, also setting the X-CSRFToken, X-Requested-With, Referer and
Sec-Fetch-* headers required by the endpoint.

The API has only PUT and GET semantics — to "delete" all rules for a
pattern or branch type, send a PUT with an empty values list:
--body '{"values":[]}'
`,
	}

	cmd.AddCommand(
		newProjectBranchRestrictionsReplaceProjectBranchRestrictionsByBranchTypeCmd(),
		newProjectBranchRestrictionsReplaceProjectBranchRestrictionsByPatternCmd(),
		newProjectBranchRestrictionsGetProjectBranchRestrictionsGroupedByBranchCmd(),
	)

	return cmd
}

// newProjectBranchRestrictionsReplaceProjectBranchRestrictionsByBranchTypeCmd returns the "project-branch-restrictions replace-project-branch-restrictions-by-branch-type" cobra command.
// operationId: replaceProjectBranchRestrictionsByBranchType
func newProjectBranchRestrictionsReplaceProjectBranchRestrictionsByBranchTypeCmd() *cobra.Command {
	var (
		workspace  string
		projectKey string
		branchType string
		bodyValues string
		body       string
	)

	cmd := &cobra.Command{
		Use:   "replace-project-branch-restrictions-by-branch-type",
		Short: `Replace project branch restrictions matched by branching-model branch type`,
		Long: `Replaces the full set of project-level branch restriction rules that
match the given branching-model branch type. The "branch_match_kind"
of every rule in the request body must be "branching_model".

This single endpoint covers Create, Update, and Delete:
  * To create or update rules for a branch type, send the full
    desired values list.
  * To delete all rules for a branch type, send {"values": []}.
`,
		RunE: func(cmd *cobra.Command, args []string) error {
			pathParams := map[string]string{
				"workspace":   workspace,
				"project_key": projectKey,
				"branch_type": branchType,
			}
			handlers.InferRepoContext(pathParams)
			if pathParams["workspace"] == "" {
				return fmt.Errorf("--workspace is required")
			}
			if pathParams["project_key"] == "" {
				return fmt.Errorf("--project-key is required")
			}
			if pathParams["branch_type"] == "" {
				return fmt.Errorf("--branch-type is required")
			}
			c, err := client.NewClient()
			if err != nil {
				return err
			}
			queryParams := map[string]string{}
			if body == "" {
				bodyObj := map[string]any{}
				if bodyValues != "" {
					handlers.SetNested(bodyObj, "values", bodyValues)
				}
				if len(bodyObj) > 0 {
					b, _ := json.Marshal(bodyObj)
					body = string(b)
				}
			}
			return handlers.Dispatch(context.Background(), c, handlers.Request{
				Method:      "PUT",
				URLTemplate: "https://bitbucket.org/!api/internal/workspaces/{workspace}/projects/{project_key}/branch-restrictions/by-branch-type/{branch_type}",
				PathParams:  pathParams,
				QueryParams: queryParams,
				Body:        body,
				All:         false,
			})
		},
	}
	cmd.Flags().StringVar(&workspace, "workspace", "", "workspace (path parameter)")
	cmd.Flags().StringVar(&projectKey, "project-key", "", "project_key (path parameter)")
	cmd.Flags().StringVar(&branchType, "branch-type", "", "branch_type (path parameter)")
	cmd.Flags().StringVar(&bodyValues, "values", "", `The full desired list of rules.`)
	cmd.Flags().StringVar(&body, "body", "", "Raw JSON request body (advanced)")
	return cmd
}

// newProjectBranchRestrictionsReplaceProjectBranchRestrictionsByPatternCmd returns the "project-branch-restrictions replace-project-branch-restrictions-by-pattern" cobra command.
// operationId: replaceProjectBranchRestrictionsByPattern
func newProjectBranchRestrictionsReplaceProjectBranchRestrictionsByPatternCmd() *cobra.Command {
	var (
		workspace  string
		projectKey string
		pattern    string
		bodyValues string
		body       string
	)

	cmd := &cobra.Command{
		Use:   "replace-project-branch-restrictions-by-pattern",
		Short: `Replace project branch restrictions matched by glob pattern`,
		Long: `Replaces the full set of project-level branch restriction rules that
match the given branch glob pattern. The "branch_match_kind" of every
rule in the request body must be "glob".

This single endpoint covers Create, Update, and Delete:
  * To create or update rules for a pattern, send the full desired
    values list.
  * To delete all rules for a pattern, send {"values": []}.
`,
		RunE: func(cmd *cobra.Command, args []string) error {
			pathParams := map[string]string{
				"workspace":   workspace,
				"project_key": projectKey,
				"pattern":     pattern,
			}
			handlers.InferRepoContext(pathParams)
			if pathParams["workspace"] == "" {
				return fmt.Errorf("--workspace is required")
			}
			if pathParams["project_key"] == "" {
				return fmt.Errorf("--project-key is required")
			}
			if pathParams["pattern"] == "" {
				return fmt.Errorf("--pattern is required")
			}
			c, err := client.NewClient()
			if err != nil {
				return err
			}
			queryParams := map[string]string{}
			if body == "" {
				bodyObj := map[string]any{}
				if bodyValues != "" {
					handlers.SetNested(bodyObj, "values", bodyValues)
				}
				if len(bodyObj) > 0 {
					b, _ := json.Marshal(bodyObj)
					body = string(b)
				}
			}
			return handlers.Dispatch(context.Background(), c, handlers.Request{
				Method:      "PUT",
				URLTemplate: "https://bitbucket.org/!api/internal/workspaces/{workspace}/projects/{project_key}/branch-restrictions/by-pattern/{pattern}",
				PathParams:  pathParams,
				QueryParams: queryParams,
				Body:        body,
				All:         false,
			})
		},
	}
	cmd.Flags().StringVar(&workspace, "workspace", "", "workspace (path parameter)")
	cmd.Flags().StringVar(&projectKey, "project-key", "", "project_key (path parameter)")
	cmd.Flags().StringVar(&pattern, "pattern", "", "pattern (path parameter)")
	cmd.Flags().StringVar(&bodyValues, "values", "", `The full desired list of rules.`)
	cmd.Flags().StringVar(&body, "body", "", "Raw JSON request body (advanced)")
	return cmd
}

// newProjectBranchRestrictionsGetProjectBranchRestrictionsGroupedByBranchCmd returns the "project-branch-restrictions get-project-branch-restrictions-grouped-by-branch" cobra command.
// operationId: getProjectBranchRestrictionsGroupedByBranch
func newProjectBranchRestrictionsGetProjectBranchRestrictionsGroupedByBranchCmd() *cobra.Command {
	var (
		workspace  string
		projectKey string
	)

	cmd := &cobra.Command{
		Use:   "get-project-branch-restrictions-grouped-by-branch",
		Short: `List project branch restrictions grouped by branch`,
		Long: `Returns the project-level branch restriction rules grouped by the
branch they apply to. Use this as the "Read" / "List" operation when
managing project-level branch restrictions.
`,
		RunE: func(cmd *cobra.Command, args []string) error {
			pathParams := map[string]string{
				"workspace":   workspace,
				"project_key": projectKey,
			}
			handlers.InferRepoContext(pathParams)
			if pathParams["workspace"] == "" {
				return fmt.Errorf("--workspace is required")
			}
			if pathParams["project_key"] == "" {
				return fmt.Errorf("--project-key is required")
			}
			c, err := client.NewClient()
			if err != nil {
				return err
			}
			queryParams := map[string]string{}
			body := ""
			return handlers.Dispatch(context.Background(), c, handlers.Request{
				Method:      "GET",
				URLTemplate: "https://bitbucket.org/!api/internal/workspaces/{workspace}/projects/{project_key}/branch-restrictions/group-by-branch/",
				PathParams:  pathParams,
				QueryParams: queryParams,
				Body:        body,
				All:         false,
			})
		},
	}
	cmd.Flags().StringVar(&workspace, "workspace", "", "workspace (path parameter)")
	cmd.Flags().StringVar(&projectKey, "project-key", "", "project_key (path parameter)")
	return cmd
}
