// Code generated by scripts/gen_mcptools/main.go DO NOT EDIT.
// Source: schema/internal-branch-restrictions-schema.yaml
//
// This file is regenerated whenever the schema changes in CI.
// Do not edit manually — run: go run scripts/gen_mcptools/main.go schema/internal-branch-restrictions-schema.yaml <output.go>

package mcptools

func init() {
	AllToolGroups = append(AllToolGroups, ProjectBranchRestrictionsToolGroup)
}

// ProjectBranchRestrictionsToolGroup contains the MCP tool definition for the "bitbucket_project-branch-restrictions" tool group.
var ProjectBranchRestrictionsToolGroup = ToolGroup{
	Name: `bitbucket_project-branch-restrictions`,
	Description: `Manage Bitbucket project-level branch restrictions (internal API)

Available operations:
- replaceProjectBranchRestrictionsByBranchType: Replace project branch restrictions matched by branching-model branch type [PUT]
- replaceProjectBranchRestrictionsByPattern: Replace project branch restrictions matched by glob pattern [PUT]
- getProjectBranchRestrictionsGroupedByBranch: List project branch restrictions grouped by branch [GET]
`,
	Operations: []OperationDef{
		{
			OperationID: `replaceProjectBranchRestrictionsByBranchType`,
			Method:      `PUT`,
			Path:        `https://bitbucket.org/!api/internal/workspaces/{workspace}/projects/{project_key}/branch-restrictions/by-branch-type/{branch_type}`,
			Summary:     `Replace project branch restrictions matched by branching-model branch type`,
			Description: `Replaces the full set of project-level branch restriction rules that
match the given branching-model branch type. The "branch_match_kind"
of every rule in the request body must be "branching_model".

This single endpoint covers Create, Update, and Delete:
  * To create or update rules for a branch type, send the full
    desired values list.
  * To delete all rules for a branch type, send {"values": []}.
`,
			Params: []ParamDef{
				{Name: `workspace`, In: `path`, Type: `string`, Required: true},
				{Name: `project_key`, In: `path`, Type: `string`, Required: true},
				{Name: `branch_type`, In: `path`, Type: `string`, Required: true},
			},
			BodyFields: []BodyFieldDef{
				{Path: `values`, Type: `string`, Desc: `The full desired list of rules.`},
			},
			HasBody:   true,
			Paginated: false,
		},
		{
			OperationID: `replaceProjectBranchRestrictionsByPattern`,
			Method:      `PUT`,
			Path:        `https://bitbucket.org/!api/internal/workspaces/{workspace}/projects/{project_key}/branch-restrictions/by-pattern/{pattern}`,
			Summary:     `Replace project branch restrictions matched by glob pattern`,
			Description: `Replaces the full set of project-level branch restriction rules that
match the given branch glob pattern. The "branch_match_kind" of every
rule in the request body must be "glob".

This single endpoint covers Create, Update, and Delete:
  * To create or update rules for a pattern, send the full desired
    values list.
  * To delete all rules for a pattern, send {"values": []}.
`,
			Params: []ParamDef{
				{Name: `workspace`, In: `path`, Type: `string`, Required: true},
				{Name: `project_key`, In: `path`, Type: `string`, Required: true},
				{Name: `pattern`, In: `path`, Type: `string`, Required: true},
			},
			BodyFields: []BodyFieldDef{
				{Path: `values`, Type: `string`, Desc: `The full desired list of rules.`},
			},
			HasBody:   true,
			Paginated: false,
		},
		{
			OperationID: `getProjectBranchRestrictionsGroupedByBranch`,
			Method:      `GET`,
			Path:        `https://bitbucket.org/!api/internal/workspaces/{workspace}/projects/{project_key}/branch-restrictions/group-by-branch/`,
			Summary:     `List project branch restrictions grouped by branch`,
			Description: `Returns the project-level branch restriction rules grouped by the
branch they apply to. Use this as the "Read" / "List" operation when
managing project-level branch restrictions.
`,
			Params: []ParamDef{
				{Name: `workspace`, In: `path`, Type: `string`, Required: true},
				{Name: `project_key`, In: `path`, Type: `string`, Required: true},
			},
			BodyFields: []BodyFieldDef{},
			HasBody:    false,
			Paginated:  false,
		},
	},
}
