// Code generated by scripts/gen_terraform/main.go DO NOT EDIT.
// Source: schema/addon-schema.yaml
//
// This file is regenerated whenever the schema changes in CI.
// Do not edit manually — run: go run scripts/gen_terraform/main.go schema/addon-schema.yaml <output.go>

package tfprovider

func init() {
	RegisterResourceGroup(AddonResourceGroup)
}

// AddonResourceGroup contains the Terraform resource definition for the "addon" resource group.
var AddonResourceGroup = ResourceGroup{
	TypeName: `addon`,
	Description: `Manage Bitbucket Connect addons

Available operations:
- updateAnInstalledApp: Update an installed app [PUT]
- deleteAnApp: Delete an app [DELETE]
- getTheClientKeyOfAConnectAddon: Get the client key of a Connect addon [GET]
`,
	Category: `Addon`,
	Ops: MapCRUDOps(`addon`, []OperationDef{
		{
			OperationID:    `updateAnInstalledApp`,
			Method:         `PUT`,
			Path:           `/addon`,
			Summary:        `Update an installed app`,
			Description:    "Updates the application installation for the user.\n\nThis endpoint is intended to be used by Bitbucket Connect apps\nand only supports JWT authentication -- that is how Bitbucket\nidentifies the particular installation of the app. Developers\nwith applications registered in the \"Develop Apps\" section\nof Bitbucket need not use this endpoint as updates for those\napplications can be sent out via the UI of that section.\n\nPassing an empty body will update the installation using the\nexisting descriptor URL.\n\n```\n$ curl -X PUT https://api.bitbucket.org/2.0/addon \\\n  -H \"Authorization: JWT <JWT Token>\" \\\n  --header \"Content-Type: application/json\" \\\n  --data '{}'\n```\n\nThe new `descriptor` for the installation can be also provided\nin the body directly.\n\n```\n$ curl -X PUT https://api.bitbucket.org/2.0/addon \\\n  -H \"Authorization: JWT <JWT Token>\" \\\n  --header \"Content-Type: application/json\" \\\n  --data '{\"descriptor\": $NEW_DESCRIPTOR}'\n```\n\nIn both these modes the URL of the descriptor cannot be changed. To\nchange the descriptor location and upgrade an installation\nthe request must be made exclusively with a `descriptor_url`.\n\n ```\n$ curl -X PUT https://api.bitbucket.org/2.0/addon \\\n  -H \"Authorization: JWT <JWT Token>\" \\\n  --header \"Content-Type: application/json\" \\\n  --data '{\"descriptor_url\": $NEW_URL}'\n```\n\nThe `descriptor_url` must exactly match the marketplace registration\nthat Atlassian has for the application. Contact your Atlassian\ndeveloper advocate to update this registration. Once the registration\nhas been updated you may call this resource for each installation.\n\nNote that the scopes of the application cannot be increased\nin the new descriptor nor reduced to none.",
			Params:         []ParamDef{},
			BodyFields:     []BodyFieldDef{},
			ResponseFields: []BodyFieldDef{},
			HasBody:        false,
			Paginated:      false,
			DocURL:         `https://developer.atlassian.com/cloud/bitbucket/rest/api-group-addon/#api-addon-put`,
		},
		{
			OperationID:    `deleteAnApp`,
			Method:         `DELETE`,
			Path:           `/addon`,
			Summary:        `Delete an app`,
			Description:    "Deletes the application for the user.\n\nThis endpoint is intended to be used by Bitbucket Connect apps\nand only supports JWT authentication -- that is how Bitbucket\nidentifies the particular installation of the app. Developers\nwith applications registered in the \"Develop Apps\" section\nof Bitbucket Marketplace need not use this endpoint as\nupdates for those applications can be sent out via the\nUI of that section.\n\n```\n$ curl -X DELETE https://api.bitbucket.org/2.0/addon \\\n  -H \"Authorization: JWT <JWT Token>\"\n```",
			Params:         []ParamDef{},
			BodyFields:     []BodyFieldDef{},
			ResponseFields: []BodyFieldDef{},
			HasBody:        false,
			Paginated:      false,
			DocURL:         `https://developer.atlassian.com/cloud/bitbucket/rest/api-group-addon/#api-addon-delete`,
		},
		{
			OperationID: `getTheClientKeyOfAConnectAddon`,
			Method:      `GET`,
			Path:        `/addon/{addon_key}/client-key`,
			Summary:     `Get the client key of a Connect addon`,
			Description: "Get the client key of the Connect addon associated with a Forge app install via forgeAppId linkage.\n\nThis endpoint is part of the Connect -> Forge migration tooling. It is intended to be used by a Forge app\nusing `asApp().requestBitbucket()` only.\nPrerequisite: app developer needs to register the linkage between their Connect and Forge app by setting\n`forgeAppId` in the Connect addon descriptor to `app.id` from Forge app manifest, then update the installations.\nIf the request came from an installation of a registered Forge app, the client key of the linked Connect addon\ninstalled in the same workspace will be returned.\n\n```\napi.asApp().requestBitbucket(route`/2.0/addon/{addon-key}/client-key`)\n```",
			Params: []ParamDef{
				{Name: `addon_key`, In: `path`, Type: `string`, Required: true},
			},
			BodyFields:     []BodyFieldDef{},
			ResponseFields: []BodyFieldDef{},
			HasBody:        false,
			Paginated:      false,
			Scopes: []string{
				`admin:workspace:bitbucket`,
			},
			DocURL: `https://developer.atlassian.com/cloud/bitbucket/rest/api-group-addon/#api-addon-addon-key-client-key-get`,
		},
	}),
	AllOps: []OperationDef{
		{
			OperationID:    `updateAnInstalledApp`,
			Method:         `PUT`,
			Path:           `/addon`,
			Summary:        `Update an installed app`,
			Description:    "Updates the application installation for the user.\n\nThis endpoint is intended to be used by Bitbucket Connect apps\nand only supports JWT authentication -- that is how Bitbucket\nidentifies the particular installation of the app. Developers\nwith applications registered in the \"Develop Apps\" section\nof Bitbucket need not use this endpoint as updates for those\napplications can be sent out via the UI of that section.\n\nPassing an empty body will update the installation using the\nexisting descriptor URL.\n\n```\n$ curl -X PUT https://api.bitbucket.org/2.0/addon \\\n  -H \"Authorization: JWT <JWT Token>\" \\\n  --header \"Content-Type: application/json\" \\\n  --data '{}'\n```\n\nThe new `descriptor` for the installation can be also provided\nin the body directly.\n\n```\n$ curl -X PUT https://api.bitbucket.org/2.0/addon \\\n  -H \"Authorization: JWT <JWT Token>\" \\\n  --header \"Content-Type: application/json\" \\\n  --data '{\"descriptor\": $NEW_DESCRIPTOR}'\n```\n\nIn both these modes the URL of the descriptor cannot be changed. To\nchange the descriptor location and upgrade an installation\nthe request must be made exclusively with a `descriptor_url`.\n\n ```\n$ curl -X PUT https://api.bitbucket.org/2.0/addon \\\n  -H \"Authorization: JWT <JWT Token>\" \\\n  --header \"Content-Type: application/json\" \\\n  --data '{\"descriptor_url\": $NEW_URL}'\n```\n\nThe `descriptor_url` must exactly match the marketplace registration\nthat Atlassian has for the application. Contact your Atlassian\ndeveloper advocate to update this registration. Once the registration\nhas been updated you may call this resource for each installation.\n\nNote that the scopes of the application cannot be increased\nin the new descriptor nor reduced to none.",
			Params:         []ParamDef{},
			BodyFields:     []BodyFieldDef{},
			ResponseFields: []BodyFieldDef{},
			HasBody:        false,
			Paginated:      false,
			DocURL:         `https://developer.atlassian.com/cloud/bitbucket/rest/api-group-addon/#api-addon-put`,
		},
		{
			OperationID:    `deleteAnApp`,
			Method:         `DELETE`,
			Path:           `/addon`,
			Summary:        `Delete an app`,
			Description:    "Deletes the application for the user.\n\nThis endpoint is intended to be used by Bitbucket Connect apps\nand only supports JWT authentication -- that is how Bitbucket\nidentifies the particular installation of the app. Developers\nwith applications registered in the \"Develop Apps\" section\nof Bitbucket Marketplace need not use this endpoint as\nupdates for those applications can be sent out via the\nUI of that section.\n\n```\n$ curl -X DELETE https://api.bitbucket.org/2.0/addon \\\n  -H \"Authorization: JWT <JWT Token>\"\n```",
			Params:         []ParamDef{},
			BodyFields:     []BodyFieldDef{},
			ResponseFields: []BodyFieldDef{},
			HasBody:        false,
			Paginated:      false,
			DocURL:         `https://developer.atlassian.com/cloud/bitbucket/rest/api-group-addon/#api-addon-delete`,
		},
		{
			OperationID: `getTheClientKeyOfAConnectAddon`,
			Method:      `GET`,
			Path:        `/addon/{addon_key}/client-key`,
			Summary:     `Get the client key of a Connect addon`,
			Description: "Get the client key of the Connect addon associated with a Forge app install via forgeAppId linkage.\n\nThis endpoint is part of the Connect -> Forge migration tooling. It is intended to be used by a Forge app\nusing `asApp().requestBitbucket()` only.\nPrerequisite: app developer needs to register the linkage between their Connect and Forge app by setting\n`forgeAppId` in the Connect addon descriptor to `app.id` from Forge app manifest, then update the installations.\nIf the request came from an installation of a registered Forge app, the client key of the linked Connect addon\ninstalled in the same workspace will be returned.\n\n```\napi.asApp().requestBitbucket(route`/2.0/addon/{addon-key}/client-key`)\n```",
			Params: []ParamDef{
				{Name: `addon_key`, In: `path`, Type: `string`, Required: true},
			},
			BodyFields:     []BodyFieldDef{},
			ResponseFields: []BodyFieldDef{},
			HasBody:        false,
			Paginated:      false,
			Scopes: []string{
				`admin:workspace:bitbucket`,
			},
			DocURL: `https://developer.atlassian.com/cloud/bitbucket/rest/api-group-addon/#api-addon-addon-key-client-key-get`,
		},
	},
}
