package tfprovider

// CRUDConfig maps each resource group to its primary CRUD operation IDs.
//
// This is a hand-written configuration that selects the "main" resource
// for each group from the many sub-resource endpoints generated by the
// OpenAPI schema. The mapping is intentionally explicit to avoid fragile
// heuristics.
//
// When new resource groups are added, add an entry here. If an operation
// ID doesn't exist in the generated code, it is silently ignored.
var CRUDConfig = map[string]CRUDMapping{
	"repos": {
		Create: "createARepository",
		Read:   "getARepository",
		Update: "updateARepository",
		Delete: "deleteARepository",
		List:   "listRepositoriesInAWorkspace",
	},
	"pr": {
		Create: "createAPullRequest",
		Read:   "getAPullRequest",
		Update: "updateAPullRequest",
		List:   "listPullRequests",
	},
	"projects": {
		Create: "createAProjectInAWorkspace",
		Read:   "getAProjectForAWorkspace",
		Update: "updateAProjectForAWorkspace",
		Delete: "deleteAProjectForAWorkspace",
		List:   "listProjectsInAWorkspace",
	},
	"workspaces": {
		Read: "getAWorkspace",
		List: "listWorkspacesForUser",
	},
	"issues": {
		Create: "createAnIssue",
		Read:   "getAnIssue",
		Update: "updateAnIssue",
		Delete: "deleteAnIssue",
		List:   "listIssues",
	},
	"hooks": {
		Create: "createAWebhookForARepository",
		Read:   "getAWebhookForARepository",
		Update: "updateAWebhookForARepository",
		Delete: "deleteAWebhookForARepository",
		List:   "listWebhooksForARepository",
	},
	"snippets": {
		Create: "createASnippet",
		Read:   "getASnippet",
		Update: "updateASnippet",
		Delete: "deleteASnippet",
		List:   "listSnippets",
	},
	"refs": {
		Create: "createABranch",
		Read:   "getABranch",
		Delete: "deleteABranch",
		List:   "listBranchesAndTags",
	},
	"commits": {
		Read: "getACommit",
		List: "listCommits",
	},
	"pipelines": {
		Create: "createPipelineForRepository",
		Read:   "getPipelineForRepository",
		List:   "getPipelinesForRepository",
	},
	"deployments": {
		Create: "createEnvironment",
		Read:   "getEnvironmentForRepository",
		Delete: "deleteEnvironmentForRepository",
		List:   "getEnvironmentsForRepository",
	},
	"branch-restrictions": {
		Create: "createABranchRestrictionRule",
		Read:   "getABranchRestrictionRule",
		Update: "updateABranchRestrictionRule",
		Delete: "deleteABranchRestrictionRule",
		List:   "listBranchRestrictions",
	},
	"branching-model": {
		Read:   "getTheBranchingModelForARepository",
		Update: "updateTheBranchingModelConfigForARepository",
	},
	"commit-statuses": {
		Create: "createABuildStatusForACommit",
		Read:   "getABuildStatusForACommit",
		Update: "updateABuildStatusForACommit",
		List:   "listCommitStatusesForACommit",
	},
	"downloads": {
		Create: "uploadADownloadArtifact",
		Read:   "getADownloadArtifactLink",
		Delete: "deleteADownloadArtifact",
		List:   "listDownloadArtifacts",
	},
	"users": {
		Read: "getAUser",
		List: "listSshKeys",
	},
	"reports": {
		Create: "createOrUpdateReport",
		Read:   "getReport",
		Delete: "deleteReport",
		List:   "getReportsForCommit",
	},
	"search": {
		List: "searchWorkspace",
	},
	"properties": {
		Read:   "getRepositoryHostedPropertyValue",
		Update: "updateRepositoryHostedPropertyValue",
		Delete: "deleteRepositoryHostedPropertyValue",
	},
	"addon": {
		Update: "updateAnInstalledApp",
		Delete: "deleteAnApp",
		List:   "listLinkersForAnApp",
	},
}

// CRUDMapping holds operation IDs for each CRUD slot.
// Empty strings mean the operation is not available.
type CRUDMapping struct {
	Create string
	Read   string
	Update string
	Delete string
	List   string
}
