// Code generated by scripts/gen_terraform/main.go DO NOT EDIT.
// Source: schema/hooks-schema.yaml
//
// This file is regenerated whenever the schema changes in CI.
// Do not edit manually — run: go run scripts/gen_terraform/main.go schema/hooks-schema.yaml <output.go>

package tfprovider

func init() {
	RegisterResourceGroup(HooksResourceGroup)
}

// HooksResourceGroup contains the Terraform resource definition for the "hooks" resource group.
var HooksResourceGroup = ResourceGroup{
	TypeName: `hooks`,
	Description: `Manage Bitbucket webhooks

Available operations:
- getAWebhookResource: Get a webhook resource [GET]
- listSubscribableWebhookTypes: List subscribable webhook types [GET]
- listWebhooksForARepository: List webhooks for a repository [GET]
- createAWebhookForARepository: Create a webhook for a repository [POST]
- getAWebhookForARepository: Get a webhook for a repository [GET]
- updateAWebhookForARepository: Update a webhook for a repository [PUT]
- deleteAWebhookForARepository: Delete a webhook for a repository [DELETE]
- listWebhooksForAWorkspace: List webhooks for a workspace [GET]
- createAWebhookForAWorkspace: Create a webhook for a workspace [POST]
- getAWebhookForAWorkspace: Get a webhook for a workspace [GET]
- updateAWebhookForAWorkspace: Update a webhook for a workspace [PUT]
- deleteAWebhookForAWorkspace: Delete a webhook for a workspace [DELETE]
`,
	Category: `Webhooks`,
	Ops: MapCRUDOps(`hooks`, []OperationDef{
		{
			OperationID:    `getAWebhookResource`,
			Method:         `GET`,
			Path:           `/hook_events`,
			Summary:        `Get a webhook resource`,
			Description:    "Returns the webhook resource or subject types on which webhooks can be registered.\nEach resource/subject type contains an `events` link that returns the paginated list of specific events each individual subject type can emit.\nThis endpoint is publicly accessible and does not require authentication or scopes.",
			Params:         []ParamDef{},
			BodyFields:     []BodyFieldDef{},
			ResponseFields: []BodyFieldDef{},
			HasBody:        false,
			Paginated:      false,
			DocURL:         `https://developer.atlassian.com/cloud/bitbucket/rest/api-group-webhooks/#api-hook-events-get`,
		},
		{
			OperationID: `listSubscribableWebhookTypes`,
			Method:      `GET`,
			Path:        `/hook_events/{subject_type}`,
			Summary:     `List subscribable webhook types`,
			Description: "Returns a paginated list of all valid webhook events for the specified entity.\n**The team and user webhooks are deprecated, and you should use workspace instead. For more information, see [the announcement](https://developer.atlassian.com/cloud/bitbucket/bitbucket-api-teams-deprecation/).**\nThis is public data that does not require any scopes or authentication.\nNOTE: The example response is a truncated response object for the `workspace` `subject_type`. We return the same structure for the other `subject_type` objects.",
			Params: []ParamDef{
				{Name: `subject_type`, In: `path`, Type: `string`, Required: true},
				{Name: `page`, In: `query`, Type: `integer`, Required: false},
				{Name: `pagelen`, In: `query`, Type: `integer`, Required: false},
			},
			BodyFields: []BodyFieldDef{},
			ResponseFields: []BodyFieldDef{
				{Path: `category`, Type: `string`, Desc: `The category this event belongs to.`},
				{Path: `description`, Type: `string`, Desc: `More detailed description of the webhook event type.`},
				{Path: `event`, Type: `string`, Desc: `The event identifier. [issue:comment_created, issue:created, issue:updated, pipeline:span_created, project:updated, pullrequest:approved, pullrequest:changes_request_created, pullrequest:changes_request_removed, pullrequest:comment_created, pullrequest:comment_deleted, pullrequest:comment_reopened, pullrequest:comment_resolved, pullrequest:comment_updated, pullrequest:created, pullrequest:fulfilled, pullrequest:push, pullrequest:rejected, pullrequest:unapproved, pullrequest:updated, repo:commit_comment_created, repo:commit_status_created, repo:commit_status_updated, repo:created, repo:deleted, repo:fork, repo:imported, repo:push, repo:transfer, repo:updated]`},
				{Path: `label`, Type: `string`, Desc: `Summary of the webhook event type.`},
			},
			HasBody:   false,
			Paginated: true,
			DocURL:    `https://developer.atlassian.com/cloud/bitbucket/rest/api-group-webhooks/#api-hook-events-subject-type-get`,
		},
		{
			OperationID: `listWebhooksForARepository`,
			Method:      `GET`,
			Path:        `/repositories/{workspace}/{repo_slug}/hooks`,
			Summary:     `List webhooks for a repository`,
			Description: `Returns a paginated list of webhooks installed on this repository.
`,
			Params: []ParamDef{
				{Name: `workspace`, In: `path`, Type: `string`, Required: true},
				{Name: `repo_slug`, In: `path`, Type: `string`, Required: true},
				{Name: `page`, In: `query`, Type: `integer`, Required: false},
				{Name: `pagelen`, In: `query`, Type: `integer`, Required: false},
			},
			BodyFields: []BodyFieldDef{},
			ResponseFields: []BodyFieldDef{
				{Path: `active`, Type: `bool`, Desc: `Whether or not the webhook subscription is enabled.`},
				{Path: `description`, Type: `string`, Desc: `A user-defined description of the webhook.`},
				{Path: `events`, Type: `string`, Desc: `The events this webhook is subscribed to. [issue:comment_created, issue:created, issue:updated, pipeline:span_created, project:updated, pullrequest:approved, pullrequest:changes_request_created, pullrequest:changes_request_removed, pullrequest:comment_created, pullrequest:comment_deleted, pullrequest:comment_reopened, pullrequest:comment_resolved, pullrequest:comment_updated, pullrequest:created, pullrequest:fulfilled, pullrequest:push, pullrequest:rejected, pullrequest:unapproved, pullrequest:updated, repo:commit_comment_created, repo:commit_status_created, repo:commit_status_updated, repo:created, repo:deleted, repo:fork, repo:imported, repo:push, repo:transfer, repo:updated]`, IsArray: true},
				{Path: `secret`, Type: `string`, Desc: "The secret to associate with the hook. The secret is never returned via the API. As such, this field is only used during updates. The secret can be set to `null`` or `\"\"`` to remove the secret (or create a hook with no secret). Leaving out the secret field during updates will leave the secret unchanged. Leaving out the secret during creation will create a hook with no secret."},
				{Path: `url`, Type: `string`, Desc: `The URL events get delivered to.`},
			},
			HasBody:   false,
			Paginated: true,
			Scopes: []string{
				`read:webhook:bitbucket`,
			},
			DocURL: `https://developer.atlassian.com/cloud/bitbucket/rest/api-group-webhooks/#api-repositories-workspace-repo-slug-hooks-get`,
		},
		{
			OperationID: `createAWebhookForARepository`,
			Method:      `POST`,
			Path:        `/repositories/{workspace}/{repo_slug}/hooks`,
			Summary:     `Create a webhook for a repository`,
			Description: "Creates a new webhook on the specified repository.\n\nWorkspace webhooks are fired for events from all repositories\ncontained by that workspace.\n\nExample:\n```\n$ curl -X POST -u credentials -H 'Content-Type: application/json'\n  https://api.bitbucket.org/2.0/workspaces/my-workspace/hooks\n  -d '\n    {\n      \"description\": \"Webhook Description\",\n      \"url\": \"https://example.com/\",\n      \"active\": true,\n      \"secret\": \"this is a really bad secret\",\n      \"events\": [\n        \"repo:push\",\n        \"issue:created\",\n        \"issue:updated\"\n      ]\n    }'\n```\n\nWhen the `secret` is provided it will be used as the key to\ngenerate a HMAC digest value sent in the `X-Hub-Signature` header\nat delivery time. Passing a `null` or empty `secret` or not\npassing a `secret` will leave the webhook's secret unset.\nBitbucket only generates the `X-Hub-Signature` when the webhook's\nsecret is set.\n\nThis call requires the webhook scope, as well as any scope\nthat applies to the events that the webhook subscribes to. In the\nexample above that means: `webhook`, `repository` and `issue`.\n\nThe `url` must properly resolve and cannot be an internal,\nnon-routed address.\n",
			Params: []ParamDef{
				{Name: `workspace`, In: `path`, Type: `string`, Required: true},
				{Name: `repo_slug`, In: `path`, Type: `string`, Required: true},
			},
			BodyFields: []BodyFieldDef{
				{Path: `active`, Type: `bool`, Desc: `Whether or not the webhook subscription is enabled.`},
				{Path: `description`, Type: `string`, Desc: `A user-defined description of the webhook.`},
				{Path: `events`, Type: `string`, Desc: `The events this webhook is subscribed to. [issue:comment_created, issue:created, issue:updated, pipeline:span_created, project:updated, pullrequest:approved, pullrequest:changes_request_created, pullrequest:changes_request_removed, pullrequest:comment_created, pullrequest:comment_deleted, pullrequest:comment_reopened, pullrequest:comment_resolved, pullrequest:comment_updated, pullrequest:created, pullrequest:fulfilled, pullrequest:push, pullrequest:rejected, pullrequest:unapproved, pullrequest:updated, repo:commit_comment_created, repo:commit_status_created, repo:commit_status_updated, repo:created, repo:deleted, repo:fork, repo:imported, repo:push, repo:transfer, repo:updated]`, IsArray: true},
				{Path: `secret`, Type: `string`, Desc: "The secret to associate with the hook. The secret is never returned via the API. As such, this field is only used during updates. The secret can be set to `null`` or `\"\"`` to remove the secret (or create a hook with no secret). Leaving out the secret field during updates will leave the secret unchanged. Leaving out the secret during creation will create a hook with no secret."},
				{Path: `url`, Type: `string`, Desc: `The URL events get delivered to.`},
			},
			ResponseFields: []BodyFieldDef{
				{Path: `active`, Type: `bool`, Desc: `Whether or not the webhook subscription is enabled.`},
				{Path: `description`, Type: `string`, Desc: `A user-defined description of the webhook.`},
				{Path: `events`, Type: `string`, Desc: `The events this webhook is subscribed to. [issue:comment_created, issue:created, issue:updated, pipeline:span_created, project:updated, pullrequest:approved, pullrequest:changes_request_created, pullrequest:changes_request_removed, pullrequest:comment_created, pullrequest:comment_deleted, pullrequest:comment_reopened, pullrequest:comment_resolved, pullrequest:comment_updated, pullrequest:created, pullrequest:fulfilled, pullrequest:push, pullrequest:rejected, pullrequest:unapproved, pullrequest:updated, repo:commit_comment_created, repo:commit_status_created, repo:commit_status_updated, repo:created, repo:deleted, repo:fork, repo:imported, repo:push, repo:transfer, repo:updated]`, IsArray: true},
				{Path: `secret`, Type: `string`, Desc: "The secret to associate with the hook. The secret is never returned via the API. As such, this field is only used during updates. The secret can be set to `null`` or `\"\"`` to remove the secret (or create a hook with no secret). Leaving out the secret field during updates will leave the secret unchanged. Leaving out the secret during creation will create a hook with no secret."},
				{Path: `url`, Type: `string`, Desc: `The URL events get delivered to.`},
			},
			HasBody:   true,
			Paginated: false,
			Scopes: []string{
				`read:webhook:bitbucket`,
				`write:webhook:bitbucket`,
			},
			DocURL: `https://developer.atlassian.com/cloud/bitbucket/rest/api-group-webhooks/#api-repositories-workspace-repo-slug-hooks-post`,
		},
		{
			OperationID: `getAWebhookForARepository`,
			Method:      `GET`,
			Path:        `/repositories/{workspace}/{repo_slug}/hooks/{uid}`,
			Summary:     `Get a webhook for a repository`,
			Description: `Returns the webhook with the specified id installed on the
specified repository.
`,
			Params: []ParamDef{
				{Name: `workspace`, In: `path`, Type: `string`, Required: true},
				{Name: `repo_slug`, In: `path`, Type: `string`, Required: true},
				{Name: `uid`, In: `path`, Type: `string`, Required: true},
			},
			BodyFields: []BodyFieldDef{},
			ResponseFields: []BodyFieldDef{
				{Path: `active`, Type: `bool`, Desc: `Whether or not the webhook subscription is enabled.`},
				{Path: `description`, Type: `string`, Desc: `A user-defined description of the webhook.`},
				{Path: `events`, Type: `string`, Desc: `The events this webhook is subscribed to. [issue:comment_created, issue:created, issue:updated, pipeline:span_created, project:updated, pullrequest:approved, pullrequest:changes_request_created, pullrequest:changes_request_removed, pullrequest:comment_created, pullrequest:comment_deleted, pullrequest:comment_reopened, pullrequest:comment_resolved, pullrequest:comment_updated, pullrequest:created, pullrequest:fulfilled, pullrequest:push, pullrequest:rejected, pullrequest:unapproved, pullrequest:updated, repo:commit_comment_created, repo:commit_status_created, repo:commit_status_updated, repo:created, repo:deleted, repo:fork, repo:imported, repo:push, repo:transfer, repo:updated]`, IsArray: true},
				{Path: `secret`, Type: `string`, Desc: "The secret to associate with the hook. The secret is never returned via the API. As such, this field is only used during updates. The secret can be set to `null`` or `\"\"`` to remove the secret (or create a hook with no secret). Leaving out the secret field during updates will leave the secret unchanged. Leaving out the secret during creation will create a hook with no secret."},
				{Path: `url`, Type: `string`, Desc: `The URL events get delivered to.`},
			},
			HasBody:   false,
			Paginated: false,
			Scopes: []string{
				`read:webhook:bitbucket`,
			},
			DocURL: `https://developer.atlassian.com/cloud/bitbucket/rest/api-group-webhooks/#api-repositories-workspace-repo-slug-hooks-uid-get`,
		},
		{
			OperationID: `updateAWebhookForARepository`,
			Method:      `PUT`,
			Path:        `/repositories/{workspace}/{repo_slug}/hooks/{uid}`,
			Summary:     `Update a webhook for a repository`,
			Description: "Updates the specified webhook subscription.\n\nThe following properties can be mutated:\n\n* `description`\n* `url`\n* `secret`\n* `active`\n* `events`\n\nThe hook's secret is used as a key to generate the HMAC hex digest\nsent in the `X-Hub-Signature` header at delivery time. This\nsignature is only generated when the hook has a secret.\n\nSet the hook's secret by passing the new value in the `secret`\nfield. Passing a `null` value in the `secret` field will remove\nthe secret from the hook. The hook's secret can be left unchanged\nby not passing the `secret` field in the request.\n",
			Params: []ParamDef{
				{Name: `workspace`, In: `path`, Type: `string`, Required: true},
				{Name: `repo_slug`, In: `path`, Type: `string`, Required: true},
				{Name: `uid`, In: `path`, Type: `string`, Required: true},
			},
			BodyFields: []BodyFieldDef{
				{Path: `active`, Type: `bool`, Desc: `Whether or not the webhook subscription is enabled.`},
				{Path: `description`, Type: `string`, Desc: `A user-defined description of the webhook.`},
				{Path: `events`, Type: `string`, Desc: `The events this webhook is subscribed to. [issue:comment_created, issue:created, issue:updated, pipeline:span_created, project:updated, pullrequest:approved, pullrequest:changes_request_created, pullrequest:changes_request_removed, pullrequest:comment_created, pullrequest:comment_deleted, pullrequest:comment_reopened, pullrequest:comment_resolved, pullrequest:comment_updated, pullrequest:created, pullrequest:fulfilled, pullrequest:push, pullrequest:rejected, pullrequest:unapproved, pullrequest:updated, repo:commit_comment_created, repo:commit_status_created, repo:commit_status_updated, repo:created, repo:deleted, repo:fork, repo:imported, repo:push, repo:transfer, repo:updated]`, IsArray: true},
				{Path: `secret`, Type: `string`, Desc: "The secret to associate with the hook. The secret is never returned via the API. As such, this field is only used during updates. The secret can be set to `null`` or `\"\"`` to remove the secret (or create a hook with no secret). Leaving out the secret field during updates will leave the secret unchanged. Leaving out the secret during creation will create a hook with no secret."},
				{Path: `url`, Type: `string`, Desc: `The URL events get delivered to.`},
			},
			ResponseFields: []BodyFieldDef{
				{Path: `active`, Type: `bool`, Desc: `Whether or not the webhook subscription is enabled.`},
				{Path: `description`, Type: `string`, Desc: `A user-defined description of the webhook.`},
				{Path: `events`, Type: `string`, Desc: `The events this webhook is subscribed to. [issue:comment_created, issue:created, issue:updated, pipeline:span_created, project:updated, pullrequest:approved, pullrequest:changes_request_created, pullrequest:changes_request_removed, pullrequest:comment_created, pullrequest:comment_deleted, pullrequest:comment_reopened, pullrequest:comment_resolved, pullrequest:comment_updated, pullrequest:created, pullrequest:fulfilled, pullrequest:push, pullrequest:rejected, pullrequest:unapproved, pullrequest:updated, repo:commit_comment_created, repo:commit_status_created, repo:commit_status_updated, repo:created, repo:deleted, repo:fork, repo:imported, repo:push, repo:transfer, repo:updated]`, IsArray: true},
				{Path: `secret`, Type: `string`, Desc: "The secret to associate with the hook. The secret is never returned via the API. As such, this field is only used during updates. The secret can be set to `null`` or `\"\"`` to remove the secret (or create a hook with no secret). Leaving out the secret field during updates will leave the secret unchanged. Leaving out the secret during creation will create a hook with no secret."},
				{Path: `url`, Type: `string`, Desc: `The URL events get delivered to.`},
			},
			HasBody:   true,
			Paginated: false,
			Scopes: []string{
				`read:webhook:bitbucket`,
				`write:webhook:bitbucket`,
			},
			DocURL: `https://developer.atlassian.com/cloud/bitbucket/rest/api-group-webhooks/#api-repositories-workspace-repo-slug-hooks-uid-put`,
		},
		{
			OperationID: `deleteAWebhookForARepository`,
			Method:      `DELETE`,
			Path:        `/repositories/{workspace}/{repo_slug}/hooks/{uid}`,
			Summary:     `Delete a webhook for a repository`,
			Description: `Deletes the specified webhook subscription from the given
repository.
`,
			Params: []ParamDef{
				{Name: `workspace`, In: `path`, Type: `string`, Required: true},
				{Name: `repo_slug`, In: `path`, Type: `string`, Required: true},
				{Name: `uid`, In: `path`, Type: `string`, Required: true},
			},
			BodyFields:     []BodyFieldDef{},
			ResponseFields: []BodyFieldDef{},
			HasBody:        false,
			Paginated:      false,
			Scopes: []string{
				`delete:webhook:bitbucket`,
			},
			DocURL: `https://developer.atlassian.com/cloud/bitbucket/rest/api-group-webhooks/#api-repositories-workspace-repo-slug-hooks-uid-delete`,
		},
		{
			OperationID: `listWebhooksForAWorkspace`,
			Method:      `GET`,
			Path:        `/workspaces/{workspace}/hooks`,
			Summary:     `List webhooks for a workspace`,
			Description: `Returns a paginated list of webhooks installed on this workspace.`,
			Params: []ParamDef{
				{Name: `workspace`, In: `path`, Type: `string`, Required: true},
				{Name: `page`, In: `query`, Type: `integer`, Required: false},
				{Name: `pagelen`, In: `query`, Type: `integer`, Required: false},
			},
			BodyFields: []BodyFieldDef{},
			ResponseFields: []BodyFieldDef{
				{Path: `active`, Type: `bool`, Desc: `Whether or not the webhook subscription is enabled.`},
				{Path: `description`, Type: `string`, Desc: `A user-defined description of the webhook.`},
				{Path: `events`, Type: `string`, Desc: `The events this webhook is subscribed to. [issue:comment_created, issue:created, issue:updated, pipeline:span_created, project:updated, pullrequest:approved, pullrequest:changes_request_created, pullrequest:changes_request_removed, pullrequest:comment_created, pullrequest:comment_deleted, pullrequest:comment_reopened, pullrequest:comment_resolved, pullrequest:comment_updated, pullrequest:created, pullrequest:fulfilled, pullrequest:push, pullrequest:rejected, pullrequest:unapproved, pullrequest:updated, repo:commit_comment_created, repo:commit_status_created, repo:commit_status_updated, repo:created, repo:deleted, repo:fork, repo:imported, repo:push, repo:transfer, repo:updated]`, IsArray: true},
				{Path: `secret`, Type: `string`, Desc: "The secret to associate with the hook. The secret is never returned via the API. As such, this field is only used during updates. The secret can be set to `null`` or `\"\"`` to remove the secret (or create a hook with no secret). Leaving out the secret field during updates will leave the secret unchanged. Leaving out the secret during creation will create a hook with no secret."},
				{Path: `url`, Type: `string`, Desc: `The URL events get delivered to.`},
			},
			HasBody:   false,
			Paginated: true,
			Scopes: []string{
				`read:webhook:bitbucket`,
			},
			DocURL: `https://developer.atlassian.com/cloud/bitbucket/rest/api-group-webhooks/#api-workspaces-workspace-hooks-get`,
		},
		{
			OperationID: `createAWebhookForAWorkspace`,
			Method:      `POST`,
			Path:        `/workspaces/{workspace}/hooks`,
			Summary:     `Create a webhook for a workspace`,
			Description: "Creates a new webhook on the specified workspace.\n\nWorkspace webhooks are fired for events from all repositories\ncontained by that workspace.\n\nExample:\n```\n$ curl -X POST -u credentials -H 'Content-Type: application/json'\n  https://api.bitbucket.org/2.0/workspaces/my-workspace/hooks\n  -d '\n    {\n      \"description\": \"Webhook Description\",\n      \"url\": \"https://example.com/\",\n      \"active\": true,\n      \"secret\": \"this is a really bad secret\",\n      \"events\": [\n        \"repo:push\",\n        \"issue:created\",\n        \"issue:updated\"\n      ]\n    }'\n```\n\nWhen the `secret` is provided it will be used as the key to\ngenerate a HMAC digest value sent in the `X-Hub-Signature` header\nat delivery time. Passing a `null` or empty `secret` or not\npassing a `secret` will leave the webhook's secret unset.\nBitbucket only generates the `X-Hub-Signature` when the webhook's\nsecret is set.\n\nThis call requires the webhook scope, as well as any scope\nthat applies to the events that the webhook subscribes to. In the\nexample above that means: `webhook`, `repository` and `issue`.\n\nThe `url` must properly resolve and cannot be an internal,\nnon-routed address.\n\nOnly workspace owners can install webhooks on workspaces.\n",
			Params: []ParamDef{
				{Name: `workspace`, In: `path`, Type: `string`, Required: true},
			},
			BodyFields: []BodyFieldDef{
				{Path: `active`, Type: `bool`, Desc: `Whether or not the webhook subscription is enabled.`},
				{Path: `description`, Type: `string`, Desc: `A user-defined description of the webhook.`},
				{Path: `events`, Type: `string`, Desc: `The events this webhook is subscribed to. [issue:comment_created, issue:created, issue:updated, pipeline:span_created, project:updated, pullrequest:approved, pullrequest:changes_request_created, pullrequest:changes_request_removed, pullrequest:comment_created, pullrequest:comment_deleted, pullrequest:comment_reopened, pullrequest:comment_resolved, pullrequest:comment_updated, pullrequest:created, pullrequest:fulfilled, pullrequest:push, pullrequest:rejected, pullrequest:unapproved, pullrequest:updated, repo:commit_comment_created, repo:commit_status_created, repo:commit_status_updated, repo:created, repo:deleted, repo:fork, repo:imported, repo:push, repo:transfer, repo:updated]`, IsArray: true},
				{Path: `secret`, Type: `string`, Desc: "The secret to associate with the hook. The secret is never returned via the API. As such, this field is only used during updates. The secret can be set to `null`` or `\"\"`` to remove the secret (or create a hook with no secret). Leaving out the secret field during updates will leave the secret unchanged. Leaving out the secret during creation will create a hook with no secret."},
				{Path: `url`, Type: `string`, Desc: `The URL events get delivered to.`},
			},
			ResponseFields: []BodyFieldDef{
				{Path: `active`, Type: `bool`, Desc: `Whether or not the webhook subscription is enabled.`},
				{Path: `description`, Type: `string`, Desc: `A user-defined description of the webhook.`},
				{Path: `events`, Type: `string`, Desc: `The events this webhook is subscribed to. [issue:comment_created, issue:created, issue:updated, pipeline:span_created, project:updated, pullrequest:approved, pullrequest:changes_request_created, pullrequest:changes_request_removed, pullrequest:comment_created, pullrequest:comment_deleted, pullrequest:comment_reopened, pullrequest:comment_resolved, pullrequest:comment_updated, pullrequest:created, pullrequest:fulfilled, pullrequest:push, pullrequest:rejected, pullrequest:unapproved, pullrequest:updated, repo:commit_comment_created, repo:commit_status_created, repo:commit_status_updated, repo:created, repo:deleted, repo:fork, repo:imported, repo:push, repo:transfer, repo:updated]`, IsArray: true},
				{Path: `secret`, Type: `string`, Desc: "The secret to associate with the hook. The secret is never returned via the API. As such, this field is only used during updates. The secret can be set to `null`` or `\"\"`` to remove the secret (or create a hook with no secret). Leaving out the secret field during updates will leave the secret unchanged. Leaving out the secret during creation will create a hook with no secret."},
				{Path: `url`, Type: `string`, Desc: `The URL events get delivered to.`},
			},
			HasBody:   true,
			Paginated: false,
			Scopes: []string{
				`read:webhook:bitbucket`,
				`write:webhook:bitbucket`,
			},
			DocURL: `https://developer.atlassian.com/cloud/bitbucket/rest/api-group-webhooks/#api-workspaces-workspace-hooks-post`,
		},
		{
			OperationID: `getAWebhookForAWorkspace`,
			Method:      `GET`,
			Path:        `/workspaces/{workspace}/hooks/{uid}`,
			Summary:     `Get a webhook for a workspace`,
			Description: `Returns the webhook with the specified id installed on the
specified workspace.
`,
			Params: []ParamDef{
				{Name: `workspace`, In: `path`, Type: `string`, Required: true},
				{Name: `uid`, In: `path`, Type: `string`, Required: true},
			},
			BodyFields: []BodyFieldDef{},
			ResponseFields: []BodyFieldDef{
				{Path: `active`, Type: `bool`, Desc: `Whether or not the webhook subscription is enabled.`},
				{Path: `description`, Type: `string`, Desc: `A user-defined description of the webhook.`},
				{Path: `events`, Type: `string`, Desc: `The events this webhook is subscribed to. [issue:comment_created, issue:created, issue:updated, pipeline:span_created, project:updated, pullrequest:approved, pullrequest:changes_request_created, pullrequest:changes_request_removed, pullrequest:comment_created, pullrequest:comment_deleted, pullrequest:comment_reopened, pullrequest:comment_resolved, pullrequest:comment_updated, pullrequest:created, pullrequest:fulfilled, pullrequest:push, pullrequest:rejected, pullrequest:unapproved, pullrequest:updated, repo:commit_comment_created, repo:commit_status_created, repo:commit_status_updated, repo:created, repo:deleted, repo:fork, repo:imported, repo:push, repo:transfer, repo:updated]`, IsArray: true},
				{Path: `secret`, Type: `string`, Desc: "The secret to associate with the hook. The secret is never returned via the API. As such, this field is only used during updates. The secret can be set to `null`` or `\"\"`` to remove the secret (or create a hook with no secret). Leaving out the secret field during updates will leave the secret unchanged. Leaving out the secret during creation will create a hook with no secret."},
				{Path: `url`, Type: `string`, Desc: `The URL events get delivered to.`},
			},
			HasBody:   false,
			Paginated: false,
			Scopes: []string{
				`read:webhook:bitbucket`,
			},
			DocURL: `https://developer.atlassian.com/cloud/bitbucket/rest/api-group-webhooks/#api-workspaces-workspace-hooks-uid-get`,
		},
		{
			OperationID: `updateAWebhookForAWorkspace`,
			Method:      `PUT`,
			Path:        `/workspaces/{workspace}/hooks/{uid}`,
			Summary:     `Update a webhook for a workspace`,
			Description: "Updates the specified webhook subscription.\n\nThe following properties can be mutated:\n\n* `description`\n* `url`\n* `secret`\n* `active`\n* `events`\n\nThe hook's secret is used as a key to generate the HMAC hex digest\nsent in the X-Hub-Signature header at delivery time.\nThis signature is only generated when the hook has a secret.\n\nSet the hook's secret by passing the new value in the secret field\n. Passing a null value in the secret field will remove the secret\nfrom the hook. The hook's secret can be left unchanged by not\npassing the secret field in the request.\n",
			Params: []ParamDef{
				{Name: `workspace`, In: `path`, Type: `string`, Required: true},
				{Name: `uid`, In: `path`, Type: `string`, Required: true},
			},
			BodyFields: []BodyFieldDef{
				{Path: `active`, Type: `bool`, Desc: `Whether or not the webhook subscription is enabled.`},
				{Path: `description`, Type: `string`, Desc: `A user-defined description of the webhook.`},
				{Path: `events`, Type: `string`, Desc: `The events this webhook is subscribed to. [issue:comment_created, issue:created, issue:updated, pipeline:span_created, project:updated, pullrequest:approved, pullrequest:changes_request_created, pullrequest:changes_request_removed, pullrequest:comment_created, pullrequest:comment_deleted, pullrequest:comment_reopened, pullrequest:comment_resolved, pullrequest:comment_updated, pullrequest:created, pullrequest:fulfilled, pullrequest:push, pullrequest:rejected, pullrequest:unapproved, pullrequest:updated, repo:commit_comment_created, repo:commit_status_created, repo:commit_status_updated, repo:created, repo:deleted, repo:fork, repo:imported, repo:push, repo:transfer, repo:updated]`, IsArray: true},
				{Path: `secret`, Type: `string`, Desc: "The secret to associate with the hook. The secret is never returned via the API. As such, this field is only used during updates. The secret can be set to `null`` or `\"\"`` to remove the secret (or create a hook with no secret). Leaving out the secret field during updates will leave the secret unchanged. Leaving out the secret during creation will create a hook with no secret."},
				{Path: `url`, Type: `string`, Desc: `The URL events get delivered to.`},
			},
			ResponseFields: []BodyFieldDef{
				{Path: `active`, Type: `bool`, Desc: `Whether or not the webhook subscription is enabled.`},
				{Path: `description`, Type: `string`, Desc: `A user-defined description of the webhook.`},
				{Path: `events`, Type: `string`, Desc: `The events this webhook is subscribed to. [issue:comment_created, issue:created, issue:updated, pipeline:span_created, project:updated, pullrequest:approved, pullrequest:changes_request_created, pullrequest:changes_request_removed, pullrequest:comment_created, pullrequest:comment_deleted, pullrequest:comment_reopened, pullrequest:comment_resolved, pullrequest:comment_updated, pullrequest:created, pullrequest:fulfilled, pullrequest:push, pullrequest:rejected, pullrequest:unapproved, pullrequest:updated, repo:commit_comment_created, repo:commit_status_created, repo:commit_status_updated, repo:created, repo:deleted, repo:fork, repo:imported, repo:push, repo:transfer, repo:updated]`, IsArray: true},
				{Path: `secret`, Type: `string`, Desc: "The secret to associate with the hook. The secret is never returned via the API. As such, this field is only used during updates. The secret can be set to `null`` or `\"\"`` to remove the secret (or create a hook with no secret). Leaving out the secret field during updates will leave the secret unchanged. Leaving out the secret during creation will create a hook with no secret."},
				{Path: `url`, Type: `string`, Desc: `The URL events get delivered to.`},
			},
			HasBody:   true,
			Paginated: false,
			Scopes: []string{
				`read:webhook:bitbucket`,
				`write:webhook:bitbucket`,
			},
			DocURL: `https://developer.atlassian.com/cloud/bitbucket/rest/api-group-webhooks/#api-workspaces-workspace-hooks-uid-put`,
		},
		{
			OperationID: `deleteAWebhookForAWorkspace`,
			Method:      `DELETE`,
			Path:        `/workspaces/{workspace}/hooks/{uid}`,
			Summary:     `Delete a webhook for a workspace`,
			Description: `Deletes the specified webhook subscription from the given
workspace.
`,
			Params: []ParamDef{
				{Name: `workspace`, In: `path`, Type: `string`, Required: true},
				{Name: `uid`, In: `path`, Type: `string`, Required: true},
			},
			BodyFields:     []BodyFieldDef{},
			ResponseFields: []BodyFieldDef{},
			HasBody:        false,
			Paginated:      false,
			Scopes: []string{
				`delete:webhook:bitbucket`,
			},
			DocURL: `https://developer.atlassian.com/cloud/bitbucket/rest/api-group-webhooks/#api-workspaces-workspace-hooks-uid-delete`,
		},
	}),
	AllOps: []OperationDef{
		{
			OperationID:    `getAWebhookResource`,
			Method:         `GET`,
			Path:           `/hook_events`,
			Summary:        `Get a webhook resource`,
			Description:    "Returns the webhook resource or subject types on which webhooks can be registered.\nEach resource/subject type contains an `events` link that returns the paginated list of specific events each individual subject type can emit.\nThis endpoint is publicly accessible and does not require authentication or scopes.",
			Params:         []ParamDef{},
			BodyFields:     []BodyFieldDef{},
			ResponseFields: []BodyFieldDef{},
			HasBody:        false,
			Paginated:      false,
			DocURL:         `https://developer.atlassian.com/cloud/bitbucket/rest/api-group-webhooks/#api-hook-events-get`,
		},
		{
			OperationID: `listSubscribableWebhookTypes`,
			Method:      `GET`,
			Path:        `/hook_events/{subject_type}`,
			Summary:     `List subscribable webhook types`,
			Description: "Returns a paginated list of all valid webhook events for the specified entity.\n**The team and user webhooks are deprecated, and you should use workspace instead. For more information, see [the announcement](https://developer.atlassian.com/cloud/bitbucket/bitbucket-api-teams-deprecation/).**\nThis is public data that does not require any scopes or authentication.\nNOTE: The example response is a truncated response object for the `workspace` `subject_type`. We return the same structure for the other `subject_type` objects.",
			Params: []ParamDef{
				{Name: `subject_type`, In: `path`, Type: `string`, Required: true},
				{Name: `page`, In: `query`, Type: `integer`, Required: false},
				{Name: `pagelen`, In: `query`, Type: `integer`, Required: false},
			},
			BodyFields: []BodyFieldDef{},
			ResponseFields: []BodyFieldDef{
				{Path: `category`, Type: `string`, Desc: `The category this event belongs to.`},
				{Path: `description`, Type: `string`, Desc: `More detailed description of the webhook event type.`},
				{Path: `event`, Type: `string`, Desc: `The event identifier. [issue:comment_created, issue:created, issue:updated, pipeline:span_created, project:updated, pullrequest:approved, pullrequest:changes_request_created, pullrequest:changes_request_removed, pullrequest:comment_created, pullrequest:comment_deleted, pullrequest:comment_reopened, pullrequest:comment_resolved, pullrequest:comment_updated, pullrequest:created, pullrequest:fulfilled, pullrequest:push, pullrequest:rejected, pullrequest:unapproved, pullrequest:updated, repo:commit_comment_created, repo:commit_status_created, repo:commit_status_updated, repo:created, repo:deleted, repo:fork, repo:imported, repo:push, repo:transfer, repo:updated]`},
				{Path: `label`, Type: `string`, Desc: `Summary of the webhook event type.`},
			},
			HasBody:   false,
			Paginated: true,
			DocURL:    `https://developer.atlassian.com/cloud/bitbucket/rest/api-group-webhooks/#api-hook-events-subject-type-get`,
		},
		{
			OperationID: `listWebhooksForARepository`,
			Method:      `GET`,
			Path:        `/repositories/{workspace}/{repo_slug}/hooks`,
			Summary:     `List webhooks for a repository`,
			Description: `Returns a paginated list of webhooks installed on this repository.
`,
			Params: []ParamDef{
				{Name: `workspace`, In: `path`, Type: `string`, Required: true},
				{Name: `repo_slug`, In: `path`, Type: `string`, Required: true},
				{Name: `page`, In: `query`, Type: `integer`, Required: false},
				{Name: `pagelen`, In: `query`, Type: `integer`, Required: false},
			},
			BodyFields: []BodyFieldDef{},
			ResponseFields: []BodyFieldDef{
				{Path: `active`, Type: `bool`, Desc: `Whether or not the webhook subscription is enabled.`},
				{Path: `description`, Type: `string`, Desc: `A user-defined description of the webhook.`},
				{Path: `events`, Type: `string`, Desc: `The events this webhook is subscribed to. [issue:comment_created, issue:created, issue:updated, pipeline:span_created, project:updated, pullrequest:approved, pullrequest:changes_request_created, pullrequest:changes_request_removed, pullrequest:comment_created, pullrequest:comment_deleted, pullrequest:comment_reopened, pullrequest:comment_resolved, pullrequest:comment_updated, pullrequest:created, pullrequest:fulfilled, pullrequest:push, pullrequest:rejected, pullrequest:unapproved, pullrequest:updated, repo:commit_comment_created, repo:commit_status_created, repo:commit_status_updated, repo:created, repo:deleted, repo:fork, repo:imported, repo:push, repo:transfer, repo:updated]`, IsArray: true},
				{Path: `secret`, Type: `string`, Desc: "The secret to associate with the hook. The secret is never returned via the API. As such, this field is only used during updates. The secret can be set to `null`` or `\"\"`` to remove the secret (or create a hook with no secret). Leaving out the secret field during updates will leave the secret unchanged. Leaving out the secret during creation will create a hook with no secret."},
				{Path: `url`, Type: `string`, Desc: `The URL events get delivered to.`},
			},
			HasBody:   false,
			Paginated: true,
			Scopes: []string{
				`read:webhook:bitbucket`,
			},
			DocURL: `https://developer.atlassian.com/cloud/bitbucket/rest/api-group-webhooks/#api-repositories-workspace-repo-slug-hooks-get`,
		},
		{
			OperationID: `createAWebhookForARepository`,
			Method:      `POST`,
			Path:        `/repositories/{workspace}/{repo_slug}/hooks`,
			Summary:     `Create a webhook for a repository`,
			Description: "Creates a new webhook on the specified repository.\n\nWorkspace webhooks are fired for events from all repositories\ncontained by that workspace.\n\nExample:\n```\n$ curl -X POST -u credentials -H 'Content-Type: application/json'\n  https://api.bitbucket.org/2.0/workspaces/my-workspace/hooks\n  -d '\n    {\n      \"description\": \"Webhook Description\",\n      \"url\": \"https://example.com/\",\n      \"active\": true,\n      \"secret\": \"this is a really bad secret\",\n      \"events\": [\n        \"repo:push\",\n        \"issue:created\",\n        \"issue:updated\"\n      ]\n    }'\n```\n\nWhen the `secret` is provided it will be used as the key to\ngenerate a HMAC digest value sent in the `X-Hub-Signature` header\nat delivery time. Passing a `null` or empty `secret` or not\npassing a `secret` will leave the webhook's secret unset.\nBitbucket only generates the `X-Hub-Signature` when the webhook's\nsecret is set.\n\nThis call requires the webhook scope, as well as any scope\nthat applies to the events that the webhook subscribes to. In the\nexample above that means: `webhook`, `repository` and `issue`.\n\nThe `url` must properly resolve and cannot be an internal,\nnon-routed address.\n",
			Params: []ParamDef{
				{Name: `workspace`, In: `path`, Type: `string`, Required: true},
				{Name: `repo_slug`, In: `path`, Type: `string`, Required: true},
			},
			BodyFields: []BodyFieldDef{
				{Path: `active`, Type: `bool`, Desc: `Whether or not the webhook subscription is enabled.`},
				{Path: `description`, Type: `string`, Desc: `A user-defined description of the webhook.`},
				{Path: `events`, Type: `string`, Desc: `The events this webhook is subscribed to. [issue:comment_created, issue:created, issue:updated, pipeline:span_created, project:updated, pullrequest:approved, pullrequest:changes_request_created, pullrequest:changes_request_removed, pullrequest:comment_created, pullrequest:comment_deleted, pullrequest:comment_reopened, pullrequest:comment_resolved, pullrequest:comment_updated, pullrequest:created, pullrequest:fulfilled, pullrequest:push, pullrequest:rejected, pullrequest:unapproved, pullrequest:updated, repo:commit_comment_created, repo:commit_status_created, repo:commit_status_updated, repo:created, repo:deleted, repo:fork, repo:imported, repo:push, repo:transfer, repo:updated]`, IsArray: true},
				{Path: `secret`, Type: `string`, Desc: "The secret to associate with the hook. The secret is never returned via the API. As such, this field is only used during updates. The secret can be set to `null`` or `\"\"`` to remove the secret (or create a hook with no secret). Leaving out the secret field during updates will leave the secret unchanged. Leaving out the secret during creation will create a hook with no secret."},
				{Path: `url`, Type: `string`, Desc: `The URL events get delivered to.`},
			},
			ResponseFields: []BodyFieldDef{
				{Path: `active`, Type: `bool`, Desc: `Whether or not the webhook subscription is enabled.`},
				{Path: `description`, Type: `string`, Desc: `A user-defined description of the webhook.`},
				{Path: `events`, Type: `string`, Desc: `The events this webhook is subscribed to. [issue:comment_created, issue:created, issue:updated, pipeline:span_created, project:updated, pullrequest:approved, pullrequest:changes_request_created, pullrequest:changes_request_removed, pullrequest:comment_created, pullrequest:comment_deleted, pullrequest:comment_reopened, pullrequest:comment_resolved, pullrequest:comment_updated, pullrequest:created, pullrequest:fulfilled, pullrequest:push, pullrequest:rejected, pullrequest:unapproved, pullrequest:updated, repo:commit_comment_created, repo:commit_status_created, repo:commit_status_updated, repo:created, repo:deleted, repo:fork, repo:imported, repo:push, repo:transfer, repo:updated]`, IsArray: true},
				{Path: `secret`, Type: `string`, Desc: "The secret to associate with the hook. The secret is never returned via the API. As such, this field is only used during updates. The secret can be set to `null`` or `\"\"`` to remove the secret (or create a hook with no secret). Leaving out the secret field during updates will leave the secret unchanged. Leaving out the secret during creation will create a hook with no secret."},
				{Path: `url`, Type: `string`, Desc: `The URL events get delivered to.`},
			},
			HasBody:   true,
			Paginated: false,
			Scopes: []string{
				`read:webhook:bitbucket`,
				`write:webhook:bitbucket`,
			},
			DocURL: `https://developer.atlassian.com/cloud/bitbucket/rest/api-group-webhooks/#api-repositories-workspace-repo-slug-hooks-post`,
		},
		{
			OperationID: `getAWebhookForARepository`,
			Method:      `GET`,
			Path:        `/repositories/{workspace}/{repo_slug}/hooks/{uid}`,
			Summary:     `Get a webhook for a repository`,
			Description: `Returns the webhook with the specified id installed on the
specified repository.
`,
			Params: []ParamDef{
				{Name: `workspace`, In: `path`, Type: `string`, Required: true},
				{Name: `repo_slug`, In: `path`, Type: `string`, Required: true},
				{Name: `uid`, In: `path`, Type: `string`, Required: true},
			},
			BodyFields: []BodyFieldDef{},
			ResponseFields: []BodyFieldDef{
				{Path: `active`, Type: `bool`, Desc: `Whether or not the webhook subscription is enabled.`},
				{Path: `description`, Type: `string`, Desc: `A user-defined description of the webhook.`},
				{Path: `events`, Type: `string`, Desc: `The events this webhook is subscribed to. [issue:comment_created, issue:created, issue:updated, pipeline:span_created, project:updated, pullrequest:approved, pullrequest:changes_request_created, pullrequest:changes_request_removed, pullrequest:comment_created, pullrequest:comment_deleted, pullrequest:comment_reopened, pullrequest:comment_resolved, pullrequest:comment_updated, pullrequest:created, pullrequest:fulfilled, pullrequest:push, pullrequest:rejected, pullrequest:unapproved, pullrequest:updated, repo:commit_comment_created, repo:commit_status_created, repo:commit_status_updated, repo:created, repo:deleted, repo:fork, repo:imported, repo:push, repo:transfer, repo:updated]`, IsArray: true},
				{Path: `secret`, Type: `string`, Desc: "The secret to associate with the hook. The secret is never returned via the API. As such, this field is only used during updates. The secret can be set to `null`` or `\"\"`` to remove the secret (or create a hook with no secret). Leaving out the secret field during updates will leave the secret unchanged. Leaving out the secret during creation will create a hook with no secret."},
				{Path: `url`, Type: `string`, Desc: `The URL events get delivered to.`},
			},
			HasBody:   false,
			Paginated: false,
			Scopes: []string{
				`read:webhook:bitbucket`,
			},
			DocURL: `https://developer.atlassian.com/cloud/bitbucket/rest/api-group-webhooks/#api-repositories-workspace-repo-slug-hooks-uid-get`,
		},
		{
			OperationID: `updateAWebhookForARepository`,
			Method:      `PUT`,
			Path:        `/repositories/{workspace}/{repo_slug}/hooks/{uid}`,
			Summary:     `Update a webhook for a repository`,
			Description: "Updates the specified webhook subscription.\n\nThe following properties can be mutated:\n\n* `description`\n* `url`\n* `secret`\n* `active`\n* `events`\n\nThe hook's secret is used as a key to generate the HMAC hex digest\nsent in the `X-Hub-Signature` header at delivery time. This\nsignature is only generated when the hook has a secret.\n\nSet the hook's secret by passing the new value in the `secret`\nfield. Passing a `null` value in the `secret` field will remove\nthe secret from the hook. The hook's secret can be left unchanged\nby not passing the `secret` field in the request.\n",
			Params: []ParamDef{
				{Name: `workspace`, In: `path`, Type: `string`, Required: true},
				{Name: `repo_slug`, In: `path`, Type: `string`, Required: true},
				{Name: `uid`, In: `path`, Type: `string`, Required: true},
			},
			BodyFields: []BodyFieldDef{
				{Path: `active`, Type: `bool`, Desc: `Whether or not the webhook subscription is enabled.`},
				{Path: `description`, Type: `string`, Desc: `A user-defined description of the webhook.`},
				{Path: `events`, Type: `string`, Desc: `The events this webhook is subscribed to. [issue:comment_created, issue:created, issue:updated, pipeline:span_created, project:updated, pullrequest:approved, pullrequest:changes_request_created, pullrequest:changes_request_removed, pullrequest:comment_created, pullrequest:comment_deleted, pullrequest:comment_reopened, pullrequest:comment_resolved, pullrequest:comment_updated, pullrequest:created, pullrequest:fulfilled, pullrequest:push, pullrequest:rejected, pullrequest:unapproved, pullrequest:updated, repo:commit_comment_created, repo:commit_status_created, repo:commit_status_updated, repo:created, repo:deleted, repo:fork, repo:imported, repo:push, repo:transfer, repo:updated]`, IsArray: true},
				{Path: `secret`, Type: `string`, Desc: "The secret to associate with the hook. The secret is never returned via the API. As such, this field is only used during updates. The secret can be set to `null`` or `\"\"`` to remove the secret (or create a hook with no secret). Leaving out the secret field during updates will leave the secret unchanged. Leaving out the secret during creation will create a hook with no secret."},
				{Path: `url`, Type: `string`, Desc: `The URL events get delivered to.`},
			},
			ResponseFields: []BodyFieldDef{
				{Path: `active`, Type: `bool`, Desc: `Whether or not the webhook subscription is enabled.`},
				{Path: `description`, Type: `string`, Desc: `A user-defined description of the webhook.`},
				{Path: `events`, Type: `string`, Desc: `The events this webhook is subscribed to. [issue:comment_created, issue:created, issue:updated, pipeline:span_created, project:updated, pullrequest:approved, pullrequest:changes_request_created, pullrequest:changes_request_removed, pullrequest:comment_created, pullrequest:comment_deleted, pullrequest:comment_reopened, pullrequest:comment_resolved, pullrequest:comment_updated, pullrequest:created, pullrequest:fulfilled, pullrequest:push, pullrequest:rejected, pullrequest:unapproved, pullrequest:updated, repo:commit_comment_created, repo:commit_status_created, repo:commit_status_updated, repo:created, repo:deleted, repo:fork, repo:imported, repo:push, repo:transfer, repo:updated]`, IsArray: true},
				{Path: `secret`, Type: `string`, Desc: "The secret to associate with the hook. The secret is never returned via the API. As such, this field is only used during updates. The secret can be set to `null`` or `\"\"`` to remove the secret (or create a hook with no secret). Leaving out the secret field during updates will leave the secret unchanged. Leaving out the secret during creation will create a hook with no secret."},
				{Path: `url`, Type: `string`, Desc: `The URL events get delivered to.`},
			},
			HasBody:   true,
			Paginated: false,
			Scopes: []string{
				`read:webhook:bitbucket`,
				`write:webhook:bitbucket`,
			},
			DocURL: `https://developer.atlassian.com/cloud/bitbucket/rest/api-group-webhooks/#api-repositories-workspace-repo-slug-hooks-uid-put`,
		},
		{
			OperationID: `deleteAWebhookForARepository`,
			Method:      `DELETE`,
			Path:        `/repositories/{workspace}/{repo_slug}/hooks/{uid}`,
			Summary:     `Delete a webhook for a repository`,
			Description: `Deletes the specified webhook subscription from the given
repository.
`,
			Params: []ParamDef{
				{Name: `workspace`, In: `path`, Type: `string`, Required: true},
				{Name: `repo_slug`, In: `path`, Type: `string`, Required: true},
				{Name: `uid`, In: `path`, Type: `string`, Required: true},
			},
			BodyFields:     []BodyFieldDef{},
			ResponseFields: []BodyFieldDef{},
			HasBody:        false,
			Paginated:      false,
			Scopes: []string{
				`delete:webhook:bitbucket`,
			},
			DocURL: `https://developer.atlassian.com/cloud/bitbucket/rest/api-group-webhooks/#api-repositories-workspace-repo-slug-hooks-uid-delete`,
		},
		{
			OperationID: `listWebhooksForAWorkspace`,
			Method:      `GET`,
			Path:        `/workspaces/{workspace}/hooks`,
			Summary:     `List webhooks for a workspace`,
			Description: `Returns a paginated list of webhooks installed on this workspace.`,
			Params: []ParamDef{
				{Name: `workspace`, In: `path`, Type: `string`, Required: true},
				{Name: `page`, In: `query`, Type: `integer`, Required: false},
				{Name: `pagelen`, In: `query`, Type: `integer`, Required: false},
			},
			BodyFields: []BodyFieldDef{},
			ResponseFields: []BodyFieldDef{
				{Path: `active`, Type: `bool`, Desc: `Whether or not the webhook subscription is enabled.`},
				{Path: `description`, Type: `string`, Desc: `A user-defined description of the webhook.`},
				{Path: `events`, Type: `string`, Desc: `The events this webhook is subscribed to. [issue:comment_created, issue:created, issue:updated, pipeline:span_created, project:updated, pullrequest:approved, pullrequest:changes_request_created, pullrequest:changes_request_removed, pullrequest:comment_created, pullrequest:comment_deleted, pullrequest:comment_reopened, pullrequest:comment_resolved, pullrequest:comment_updated, pullrequest:created, pullrequest:fulfilled, pullrequest:push, pullrequest:rejected, pullrequest:unapproved, pullrequest:updated, repo:commit_comment_created, repo:commit_status_created, repo:commit_status_updated, repo:created, repo:deleted, repo:fork, repo:imported, repo:push, repo:transfer, repo:updated]`, IsArray: true},
				{Path: `secret`, Type: `string`, Desc: "The secret to associate with the hook. The secret is never returned via the API. As such, this field is only used during updates. The secret can be set to `null`` or `\"\"`` to remove the secret (or create a hook with no secret). Leaving out the secret field during updates will leave the secret unchanged. Leaving out the secret during creation will create a hook with no secret."},
				{Path: `url`, Type: `string`, Desc: `The URL events get delivered to.`},
			},
			HasBody:   false,
			Paginated: true,
			Scopes: []string{
				`read:webhook:bitbucket`,
			},
			DocURL: `https://developer.atlassian.com/cloud/bitbucket/rest/api-group-webhooks/#api-workspaces-workspace-hooks-get`,
		},
		{
			OperationID: `createAWebhookForAWorkspace`,
			Method:      `POST`,
			Path:        `/workspaces/{workspace}/hooks`,
			Summary:     `Create a webhook for a workspace`,
			Description: "Creates a new webhook on the specified workspace.\n\nWorkspace webhooks are fired for events from all repositories\ncontained by that workspace.\n\nExample:\n```\n$ curl -X POST -u credentials -H 'Content-Type: application/json'\n  https://api.bitbucket.org/2.0/workspaces/my-workspace/hooks\n  -d '\n    {\n      \"description\": \"Webhook Description\",\n      \"url\": \"https://example.com/\",\n      \"active\": true,\n      \"secret\": \"this is a really bad secret\",\n      \"events\": [\n        \"repo:push\",\n        \"issue:created\",\n        \"issue:updated\"\n      ]\n    }'\n```\n\nWhen the `secret` is provided it will be used as the key to\ngenerate a HMAC digest value sent in the `X-Hub-Signature` header\nat delivery time. Passing a `null` or empty `secret` or not\npassing a `secret` will leave the webhook's secret unset.\nBitbucket only generates the `X-Hub-Signature` when the webhook's\nsecret is set.\n\nThis call requires the webhook scope, as well as any scope\nthat applies to the events that the webhook subscribes to. In the\nexample above that means: `webhook`, `repository` and `issue`.\n\nThe `url` must properly resolve and cannot be an internal,\nnon-routed address.\n\nOnly workspace owners can install webhooks on workspaces.\n",
			Params: []ParamDef{
				{Name: `workspace`, In: `path`, Type: `string`, Required: true},
			},
			BodyFields: []BodyFieldDef{
				{Path: `active`, Type: `bool`, Desc: `Whether or not the webhook subscription is enabled.`},
				{Path: `description`, Type: `string`, Desc: `A user-defined description of the webhook.`},
				{Path: `events`, Type: `string`, Desc: `The events this webhook is subscribed to. [issue:comment_created, issue:created, issue:updated, pipeline:span_created, project:updated, pullrequest:approved, pullrequest:changes_request_created, pullrequest:changes_request_removed, pullrequest:comment_created, pullrequest:comment_deleted, pullrequest:comment_reopened, pullrequest:comment_resolved, pullrequest:comment_updated, pullrequest:created, pullrequest:fulfilled, pullrequest:push, pullrequest:rejected, pullrequest:unapproved, pullrequest:updated, repo:commit_comment_created, repo:commit_status_created, repo:commit_status_updated, repo:created, repo:deleted, repo:fork, repo:imported, repo:push, repo:transfer, repo:updated]`, IsArray: true},
				{Path: `secret`, Type: `string`, Desc: "The secret to associate with the hook. The secret is never returned via the API. As such, this field is only used during updates. The secret can be set to `null`` or `\"\"`` to remove the secret (or create a hook with no secret). Leaving out the secret field during updates will leave the secret unchanged. Leaving out the secret during creation will create a hook with no secret."},
				{Path: `url`, Type: `string`, Desc: `The URL events get delivered to.`},
			},
			ResponseFields: []BodyFieldDef{
				{Path: `active`, Type: `bool`, Desc: `Whether or not the webhook subscription is enabled.`},
				{Path: `description`, Type: `string`, Desc: `A user-defined description of the webhook.`},
				{Path: `events`, Type: `string`, Desc: `The events this webhook is subscribed to. [issue:comment_created, issue:created, issue:updated, pipeline:span_created, project:updated, pullrequest:approved, pullrequest:changes_request_created, pullrequest:changes_request_removed, pullrequest:comment_created, pullrequest:comment_deleted, pullrequest:comment_reopened, pullrequest:comment_resolved, pullrequest:comment_updated, pullrequest:created, pullrequest:fulfilled, pullrequest:push, pullrequest:rejected, pullrequest:unapproved, pullrequest:updated, repo:commit_comment_created, repo:commit_status_created, repo:commit_status_updated, repo:created, repo:deleted, repo:fork, repo:imported, repo:push, repo:transfer, repo:updated]`, IsArray: true},
				{Path: `secret`, Type: `string`, Desc: "The secret to associate with the hook. The secret is never returned via the API. As such, this field is only used during updates. The secret can be set to `null`` or `\"\"`` to remove the secret (or create a hook with no secret). Leaving out the secret field during updates will leave the secret unchanged. Leaving out the secret during creation will create a hook with no secret."},
				{Path: `url`, Type: `string`, Desc: `The URL events get delivered to.`},
			},
			HasBody:   true,
			Paginated: false,
			Scopes: []string{
				`read:webhook:bitbucket`,
				`write:webhook:bitbucket`,
			},
			DocURL: `https://developer.atlassian.com/cloud/bitbucket/rest/api-group-webhooks/#api-workspaces-workspace-hooks-post`,
		},
		{
			OperationID: `getAWebhookForAWorkspace`,
			Method:      `GET`,
			Path:        `/workspaces/{workspace}/hooks/{uid}`,
			Summary:     `Get a webhook for a workspace`,
			Description: `Returns the webhook with the specified id installed on the
specified workspace.
`,
			Params: []ParamDef{
				{Name: `workspace`, In: `path`, Type: `string`, Required: true},
				{Name: `uid`, In: `path`, Type: `string`, Required: true},
			},
			BodyFields: []BodyFieldDef{},
			ResponseFields: []BodyFieldDef{
				{Path: `active`, Type: `bool`, Desc: `Whether or not the webhook subscription is enabled.`},
				{Path: `description`, Type: `string`, Desc: `A user-defined description of the webhook.`},
				{Path: `events`, Type: `string`, Desc: `The events this webhook is subscribed to. [issue:comment_created, issue:created, issue:updated, pipeline:span_created, project:updated, pullrequest:approved, pullrequest:changes_request_created, pullrequest:changes_request_removed, pullrequest:comment_created, pullrequest:comment_deleted, pullrequest:comment_reopened, pullrequest:comment_resolved, pullrequest:comment_updated, pullrequest:created, pullrequest:fulfilled, pullrequest:push, pullrequest:rejected, pullrequest:unapproved, pullrequest:updated, repo:commit_comment_created, repo:commit_status_created, repo:commit_status_updated, repo:created, repo:deleted, repo:fork, repo:imported, repo:push, repo:transfer, repo:updated]`, IsArray: true},
				{Path: `secret`, Type: `string`, Desc: "The secret to associate with the hook. The secret is never returned via the API. As such, this field is only used during updates. The secret can be set to `null`` or `\"\"`` to remove the secret (or create a hook with no secret). Leaving out the secret field during updates will leave the secret unchanged. Leaving out the secret during creation will create a hook with no secret."},
				{Path: `url`, Type: `string`, Desc: `The URL events get delivered to.`},
			},
			HasBody:   false,
			Paginated: false,
			Scopes: []string{
				`read:webhook:bitbucket`,
			},
			DocURL: `https://developer.atlassian.com/cloud/bitbucket/rest/api-group-webhooks/#api-workspaces-workspace-hooks-uid-get`,
		},
		{
			OperationID: `updateAWebhookForAWorkspace`,
			Method:      `PUT`,
			Path:        `/workspaces/{workspace}/hooks/{uid}`,
			Summary:     `Update a webhook for a workspace`,
			Description: "Updates the specified webhook subscription.\n\nThe following properties can be mutated:\n\n* `description`\n* `url`\n* `secret`\n* `active`\n* `events`\n\nThe hook's secret is used as a key to generate the HMAC hex digest\nsent in the X-Hub-Signature header at delivery time.\nThis signature is only generated when the hook has a secret.\n\nSet the hook's secret by passing the new value in the secret field\n. Passing a null value in the secret field will remove the secret\nfrom the hook. The hook's secret can be left unchanged by not\npassing the secret field in the request.\n",
			Params: []ParamDef{
				{Name: `workspace`, In: `path`, Type: `string`, Required: true},
				{Name: `uid`, In: `path`, Type: `string`, Required: true},
			},
			BodyFields: []BodyFieldDef{
				{Path: `active`, Type: `bool`, Desc: `Whether or not the webhook subscription is enabled.`},
				{Path: `description`, Type: `string`, Desc: `A user-defined description of the webhook.`},
				{Path: `events`, Type: `string`, Desc: `The events this webhook is subscribed to. [issue:comment_created, issue:created, issue:updated, pipeline:span_created, project:updated, pullrequest:approved, pullrequest:changes_request_created, pullrequest:changes_request_removed, pullrequest:comment_created, pullrequest:comment_deleted, pullrequest:comment_reopened, pullrequest:comment_resolved, pullrequest:comment_updated, pullrequest:created, pullrequest:fulfilled, pullrequest:push, pullrequest:rejected, pullrequest:unapproved, pullrequest:updated, repo:commit_comment_created, repo:commit_status_created, repo:commit_status_updated, repo:created, repo:deleted, repo:fork, repo:imported, repo:push, repo:transfer, repo:updated]`, IsArray: true},
				{Path: `secret`, Type: `string`, Desc: "The secret to associate with the hook. The secret is never returned via the API. As such, this field is only used during updates. The secret can be set to `null`` or `\"\"`` to remove the secret (or create a hook with no secret). Leaving out the secret field during updates will leave the secret unchanged. Leaving out the secret during creation will create a hook with no secret."},
				{Path: `url`, Type: `string`, Desc: `The URL events get delivered to.`},
			},
			ResponseFields: []BodyFieldDef{
				{Path: `active`, Type: `bool`, Desc: `Whether or not the webhook subscription is enabled.`},
				{Path: `description`, Type: `string`, Desc: `A user-defined description of the webhook.`},
				{Path: `events`, Type: `string`, Desc: `The events this webhook is subscribed to. [issue:comment_created, issue:created, issue:updated, pipeline:span_created, project:updated, pullrequest:approved, pullrequest:changes_request_created, pullrequest:changes_request_removed, pullrequest:comment_created, pullrequest:comment_deleted, pullrequest:comment_reopened, pullrequest:comment_resolved, pullrequest:comment_updated, pullrequest:created, pullrequest:fulfilled, pullrequest:push, pullrequest:rejected, pullrequest:unapproved, pullrequest:updated, repo:commit_comment_created, repo:commit_status_created, repo:commit_status_updated, repo:created, repo:deleted, repo:fork, repo:imported, repo:push, repo:transfer, repo:updated]`, IsArray: true},
				{Path: `secret`, Type: `string`, Desc: "The secret to associate with the hook. The secret is never returned via the API. As such, this field is only used during updates. The secret can be set to `null`` or `\"\"`` to remove the secret (or create a hook with no secret). Leaving out the secret field during updates will leave the secret unchanged. Leaving out the secret during creation will create a hook with no secret."},
				{Path: `url`, Type: `string`, Desc: `The URL events get delivered to.`},
			},
			HasBody:   true,
			Paginated: false,
			Scopes: []string{
				`read:webhook:bitbucket`,
				`write:webhook:bitbucket`,
			},
			DocURL: `https://developer.atlassian.com/cloud/bitbucket/rest/api-group-webhooks/#api-workspaces-workspace-hooks-uid-put`,
		},
		{
			OperationID: `deleteAWebhookForAWorkspace`,
			Method:      `DELETE`,
			Path:        `/workspaces/{workspace}/hooks/{uid}`,
			Summary:     `Delete a webhook for a workspace`,
			Description: `Deletes the specified webhook subscription from the given
workspace.
`,
			Params: []ParamDef{
				{Name: `workspace`, In: `path`, Type: `string`, Required: true},
				{Name: `uid`, In: `path`, Type: `string`, Required: true},
			},
			BodyFields:     []BodyFieldDef{},
			ResponseFields: []BodyFieldDef{},
			HasBody:        false,
			Paginated:      false,
			Scopes: []string{
				`delete:webhook:bitbucket`,
			},
			DocURL: `https://developer.atlassian.com/cloud/bitbucket/rest/api-group-webhooks/#api-workspaces-workspace-hooks-uid-delete`,
		},
	},
}
