// Code generated by scripts/gen_terraform/main.go DO NOT EDIT.
// Source: schema/internal-branch-restrictions-schema.yaml
//
// This file is regenerated whenever the schema changes in CI.
// Do not edit manually — run: go run scripts/gen_terraform/main.go schema/internal-branch-restrictions-schema.yaml <output.go>

package tfprovider

func init() {
	RegisterResourceGroup(ProjectBranchRestrictionsResourceGroup)
}

// ProjectBranchRestrictionsResourceGroup contains the Terraform resource definition for the "project-branch-restrictions" resource group.
var ProjectBranchRestrictionsResourceGroup = ResourceGroup{
	TypeName: `project-branch-restrictions`,
	Description: `Manage Bitbucket project-level branch restrictions (internal API)

Available operations:
- replaceProjectBranchRestrictionsByBranchType: Replace project branch restrictions matched by branching-model branch type [PUT]
- replaceProjectBranchRestrictionsByPattern: Replace project branch restrictions matched by glob pattern [PUT]
- getProjectBranchRestrictionsGroupedByBranch: List project branch restrictions grouped by branch [GET]
`,
	Category: `Internal Project Branch Restrictions`,
	Ops: MapCRUDOps(`project-branch-restrictions`, []OperationDef{
		{
			OperationID: `replaceProjectBranchRestrictionsByBranchType`,
			Method:      `PUT`,
			Path:        `https://bitbucket.org/!api/internal/workspaces/{workspace}/projects/{project_key}/branch-restrictions/by-branch-type/{branch_type}`,
			Summary:     `Replace project branch restrictions matched by branching-model branch type`,
			Description: `Replaces the full set of project-level branch restriction rules that
match the given branching-model branch type. The "branch_match_kind"
of every rule in the request body must be "branching_model".

This single endpoint covers Create, Update, and Delete:
  * To create or update rules for a branch type, send the full
    desired values list.
  * To delete all rules for a branch type, send {"values": []}.
`,
			Params: []ParamDef{
				{Name: `workspace`, In: `path`, Type: `string`, Required: true},
				{Name: `project_key`, In: `path`, Type: `string`, Required: true},
				{Name: `branch_type`, In: `path`, Type: `string`, Required: true},
			},
			BodyFields: []BodyFieldDef{
				{Path: `values`, Type: `string`, Desc: `The full desired list of rules.`, Required: true, IsArray: true, ItemFields: []BodyFieldDef{
					{Path: `branch_match_kind`, Type: `string`, Desc: `How the rule selects branches. Must be "glob" when used with
the by-pattern endpoint, or "branching_model" with by-branch-type.
 [glob, branching_model]`, Required: true},
					{Path: `branch_type`, Type: `string`, Desc: `Branching-model branch type (when branch_match_kind=branching_model).
 [production, development, bugfix, release, feature, hotfix]`},
					{Path: `groups`, Type: `string`, Desc: `Groups exempted from the restriction. Only applies to "push" and
"restrict_merges" kinds.
`, IsArray: true, ItemFields: []BodyFieldDef{
						{Path: `owner`, Type: `string`, Desc: `owner`, IsObject: true, ItemFields: []BodyFieldDef{
							{Path: `username`, Type: `string`, Desc: `username`},
						}},
						{Path: `slug`, Type: `string`, Desc: `The group slug.`},
					}},
					{Path: `kind`, Type: `string`, Desc: `The kind of restriction.
 [push, force, delete, restrict_merges, require_tasks_to_be_completed, require_approvals_to_merge, require_default_reviewer_approvals_to_merge, require_no_changes_requested, require_passing_builds_to_merge, require_commits_behind, reset_pullrequest_approvals_on_change, smart_reset_pullrequest_approvals, reset_pullrequest_changes_requested_on_change, require_all_dependencies_merged, enforce_merge_checks, allow_auto_merge_when_builds_pass]`, Required: true},
					{Path: `pattern`, Type: `string`, Desc: `Branch glob pattern (when branch_match_kind=glob).`},
					{Path: `users`, Type: `string`, Desc: `Users exempted from the restriction. Only applies to "push" and
"restrict_merges" kinds.
`, IsArray: true, ItemFields: []BodyFieldDef{
						{Path: `uuid`, Type: `string`, Desc: `The user UUID, surrounded by curly-braces.`},
					}},
					{Path: `value`, Type: `int`, Desc: `Numeric threshold for kinds that require one (e.g.
require_approvals_to_merge, require_passing_builds_to_merge,
require_commits_behind).
`},
				}},
			},
			ResponseFields: []BodyFieldDef{
				{Path: `values`, Type: `string`, Desc: `The full desired list of rules.`, Required: true, IsArray: true, ItemFields: []BodyFieldDef{
					{Path: `branch_match_kind`, Type: `string`, Desc: `How the rule selects branches. Must be "glob" when used with
the by-pattern endpoint, or "branching_model" with by-branch-type.
 [glob, branching_model]`, Required: true},
					{Path: `branch_type`, Type: `string`, Desc: `Branching-model branch type (when branch_match_kind=branching_model).
 [production, development, bugfix, release, feature, hotfix]`},
					{Path: `groups`, Type: `string`, Desc: `Groups exempted from the restriction. Only applies to "push" and
"restrict_merges" kinds.
`, IsArray: true, ItemFields: []BodyFieldDef{
						{Path: `owner`, Type: `string`, Desc: `owner`, IsObject: true, ItemFields: []BodyFieldDef{
							{Path: `username`, Type: `string`, Desc: `username`},
						}},
						{Path: `slug`, Type: `string`, Desc: `The group slug.`},
					}},
					{Path: `kind`, Type: `string`, Desc: `The kind of restriction.
 [push, force, delete, restrict_merges, require_tasks_to_be_completed, require_approvals_to_merge, require_default_reviewer_approvals_to_merge, require_no_changes_requested, require_passing_builds_to_merge, require_commits_behind, reset_pullrequest_approvals_on_change, smart_reset_pullrequest_approvals, reset_pullrequest_changes_requested_on_change, require_all_dependencies_merged, enforce_merge_checks, allow_auto_merge_when_builds_pass]`, Required: true},
					{Path: `pattern`, Type: `string`, Desc: `Branch glob pattern (when branch_match_kind=glob).`},
					{Path: `users`, Type: `string`, Desc: `Users exempted from the restriction. Only applies to "push" and
"restrict_merges" kinds.
`, IsArray: true, ItemFields: []BodyFieldDef{
						{Path: `uuid`, Type: `string`, Desc: `The user UUID, surrounded by curly-braces.`},
					}},
					{Path: `value`, Type: `int`, Desc: `Numeric threshold for kinds that require one (e.g.
require_approvals_to_merge, require_passing_builds_to_merge,
require_commits_behind).
`},
				}},
			},
			HasBody:   true,
			Paginated: false,
			DocURL:    `https://developer.atlassian.com/cloud/bitbucket/rest/api-group-project-branch-restrictions-(internal)/#api-https:--bitbucket.org-!api-internal-workspaces-workspace-projects-project-key-branch-restrictions-by-branch-type-branch-type-put`,
		},
		{
			OperationID: `replaceProjectBranchRestrictionsByPattern`,
			Method:      `PUT`,
			Path:        `https://bitbucket.org/!api/internal/workspaces/{workspace}/projects/{project_key}/branch-restrictions/by-pattern/{pattern}`,
			Summary:     `Replace project branch restrictions matched by glob pattern`,
			Description: `Replaces the full set of project-level branch restriction rules that
match the given branch glob pattern. The "branch_match_kind" of every
rule in the request body must be "glob".

This single endpoint covers Create, Update, and Delete:
  * To create or update rules for a pattern, send the full desired
    values list.
  * To delete all rules for a pattern, send {"values": []}.
`,
			Params: []ParamDef{
				{Name: `workspace`, In: `path`, Type: `string`, Required: true},
				{Name: `project_key`, In: `path`, Type: `string`, Required: true},
				{Name: `pattern`, In: `path`, Type: `string`, Required: true},
			},
			BodyFields: []BodyFieldDef{
				{Path: `values`, Type: `string`, Desc: `The full desired list of rules.`, Required: true, IsArray: true, ItemFields: []BodyFieldDef{
					{Path: `branch_match_kind`, Type: `string`, Desc: `How the rule selects branches. Must be "glob" when used with
the by-pattern endpoint, or "branching_model" with by-branch-type.
 [glob, branching_model]`, Required: true},
					{Path: `branch_type`, Type: `string`, Desc: `Branching-model branch type (when branch_match_kind=branching_model).
 [production, development, bugfix, release, feature, hotfix]`},
					{Path: `groups`, Type: `string`, Desc: `Groups exempted from the restriction. Only applies to "push" and
"restrict_merges" kinds.
`, IsArray: true, ItemFields: []BodyFieldDef{
						{Path: `owner`, Type: `string`, Desc: `owner`, IsObject: true, ItemFields: []BodyFieldDef{
							{Path: `username`, Type: `string`, Desc: `username`},
						}},
						{Path: `slug`, Type: `string`, Desc: `The group slug.`},
					}},
					{Path: `kind`, Type: `string`, Desc: `The kind of restriction.
 [push, force, delete, restrict_merges, require_tasks_to_be_completed, require_approvals_to_merge, require_default_reviewer_approvals_to_merge, require_no_changes_requested, require_passing_builds_to_merge, require_commits_behind, reset_pullrequest_approvals_on_change, smart_reset_pullrequest_approvals, reset_pullrequest_changes_requested_on_change, require_all_dependencies_merged, enforce_merge_checks, allow_auto_merge_when_builds_pass]`, Required: true},
					{Path: `pattern`, Type: `string`, Desc: `Branch glob pattern (when branch_match_kind=glob).`},
					{Path: `users`, Type: `string`, Desc: `Users exempted from the restriction. Only applies to "push" and
"restrict_merges" kinds.
`, IsArray: true, ItemFields: []BodyFieldDef{
						{Path: `uuid`, Type: `string`, Desc: `The user UUID, surrounded by curly-braces.`},
					}},
					{Path: `value`, Type: `int`, Desc: `Numeric threshold for kinds that require one (e.g.
require_approvals_to_merge, require_passing_builds_to_merge,
require_commits_behind).
`},
				}},
			},
			ResponseFields: []BodyFieldDef{
				{Path: `values`, Type: `string`, Desc: `The full desired list of rules.`, Required: true, IsArray: true, ItemFields: []BodyFieldDef{
					{Path: `branch_match_kind`, Type: `string`, Desc: `How the rule selects branches. Must be "glob" when used with
the by-pattern endpoint, or "branching_model" with by-branch-type.
 [glob, branching_model]`, Required: true},
					{Path: `branch_type`, Type: `string`, Desc: `Branching-model branch type (when branch_match_kind=branching_model).
 [production, development, bugfix, release, feature, hotfix]`},
					{Path: `groups`, Type: `string`, Desc: `Groups exempted from the restriction. Only applies to "push" and
"restrict_merges" kinds.
`, IsArray: true, ItemFields: []BodyFieldDef{
						{Path: `owner`, Type: `string`, Desc: `owner`, IsObject: true, ItemFields: []BodyFieldDef{
							{Path: `username`, Type: `string`, Desc: `username`},
						}},
						{Path: `slug`, Type: `string`, Desc: `The group slug.`},
					}},
					{Path: `kind`, Type: `string`, Desc: `The kind of restriction.
 [push, force, delete, restrict_merges, require_tasks_to_be_completed, require_approvals_to_merge, require_default_reviewer_approvals_to_merge, require_no_changes_requested, require_passing_builds_to_merge, require_commits_behind, reset_pullrequest_approvals_on_change, smart_reset_pullrequest_approvals, reset_pullrequest_changes_requested_on_change, require_all_dependencies_merged, enforce_merge_checks, allow_auto_merge_when_builds_pass]`, Required: true},
					{Path: `pattern`, Type: `string`, Desc: `Branch glob pattern (when branch_match_kind=glob).`},
					{Path: `users`, Type: `string`, Desc: `Users exempted from the restriction. Only applies to "push" and
"restrict_merges" kinds.
`, IsArray: true, ItemFields: []BodyFieldDef{
						{Path: `uuid`, Type: `string`, Desc: `The user UUID, surrounded by curly-braces.`},
					}},
					{Path: `value`, Type: `int`, Desc: `Numeric threshold for kinds that require one (e.g.
require_approvals_to_merge, require_passing_builds_to_merge,
require_commits_behind).
`},
				}},
			},
			HasBody:   true,
			Paginated: false,
			DocURL:    `https://developer.atlassian.com/cloud/bitbucket/rest/api-group-project-branch-restrictions-(internal)/#api-https:--bitbucket.org-!api-internal-workspaces-workspace-projects-project-key-branch-restrictions-by-pattern-pattern-put`,
		},
		{
			OperationID: `getProjectBranchRestrictionsGroupedByBranch`,
			Method:      `GET`,
			Path:        `https://bitbucket.org/!api/internal/workspaces/{workspace}/projects/{project_key}/branch-restrictions/group-by-branch/`,
			Summary:     `List project branch restrictions grouped by branch`,
			Description: `Returns the project-level branch restriction rules grouped by the
branch they apply to. Use this as the "Read" / "List" operation when
managing project-level branch restrictions.
`,
			Params: []ParamDef{
				{Name: `workspace`, In: `path`, Type: `string`, Required: true},
				{Name: `project_key`, In: `path`, Type: `string`, Required: true},
			},
			BodyFields:     []BodyFieldDef{},
			ResponseFields: []BodyFieldDef{},
			HasBody:        false,
			Paginated:      false,
			DocURL:         `https://developer.atlassian.com/cloud/bitbucket/rest/api-group-project-branch-restrictions-(internal)/#api-https:--bitbucket.org-!api-internal-workspaces-workspace-projects-project-key-branch-restrictions-group-by-branch--get`,
		},
	}),
	AllOps: []OperationDef{
		{
			OperationID: `replaceProjectBranchRestrictionsByBranchType`,
			Method:      `PUT`,
			Path:        `https://bitbucket.org/!api/internal/workspaces/{workspace}/projects/{project_key}/branch-restrictions/by-branch-type/{branch_type}`,
			Summary:     `Replace project branch restrictions matched by branching-model branch type`,
			Description: `Replaces the full set of project-level branch restriction rules that
match the given branching-model branch type. The "branch_match_kind"
of every rule in the request body must be "branching_model".

This single endpoint covers Create, Update, and Delete:
  * To create or update rules for a branch type, send the full
    desired values list.
  * To delete all rules for a branch type, send {"values": []}.
`,
			Params: []ParamDef{
				{Name: `workspace`, In: `path`, Type: `string`, Required: true},
				{Name: `project_key`, In: `path`, Type: `string`, Required: true},
				{Name: `branch_type`, In: `path`, Type: `string`, Required: true},
			},
			BodyFields: []BodyFieldDef{
				{Path: `values`, Type: `string`, Desc: `The full desired list of rules.`, Required: true, IsArray: true, ItemFields: []BodyFieldDef{
					{Path: `branch_match_kind`, Type: `string`, Desc: `How the rule selects branches. Must be "glob" when used with
the by-pattern endpoint, or "branching_model" with by-branch-type.
 [glob, branching_model]`, Required: true},
					{Path: `branch_type`, Type: `string`, Desc: `Branching-model branch type (when branch_match_kind=branching_model).
 [production, development, bugfix, release, feature, hotfix]`},
					{Path: `groups`, Type: `string`, Desc: `Groups exempted from the restriction. Only applies to "push" and
"restrict_merges" kinds.
`, IsArray: true, ItemFields: []BodyFieldDef{
						{Path: `owner`, Type: `string`, Desc: `owner`, IsObject: true, ItemFields: []BodyFieldDef{
							{Path: `username`, Type: `string`, Desc: `username`},
						}},
						{Path: `slug`, Type: `string`, Desc: `The group slug.`},
					}},
					{Path: `kind`, Type: `string`, Desc: `The kind of restriction.
 [push, force, delete, restrict_merges, require_tasks_to_be_completed, require_approvals_to_merge, require_default_reviewer_approvals_to_merge, require_no_changes_requested, require_passing_builds_to_merge, require_commits_behind, reset_pullrequest_approvals_on_change, smart_reset_pullrequest_approvals, reset_pullrequest_changes_requested_on_change, require_all_dependencies_merged, enforce_merge_checks, allow_auto_merge_when_builds_pass]`, Required: true},
					{Path: `pattern`, Type: `string`, Desc: `Branch glob pattern (when branch_match_kind=glob).`},
					{Path: `users`, Type: `string`, Desc: `Users exempted from the restriction. Only applies to "push" and
"restrict_merges" kinds.
`, IsArray: true, ItemFields: []BodyFieldDef{
						{Path: `uuid`, Type: `string`, Desc: `The user UUID, surrounded by curly-braces.`},
					}},
					{Path: `value`, Type: `int`, Desc: `Numeric threshold for kinds that require one (e.g.
require_approvals_to_merge, require_passing_builds_to_merge,
require_commits_behind).
`},
				}},
			},
			ResponseFields: []BodyFieldDef{
				{Path: `values`, Type: `string`, Desc: `The full desired list of rules.`, Required: true, IsArray: true, ItemFields: []BodyFieldDef{
					{Path: `branch_match_kind`, Type: `string`, Desc: `How the rule selects branches. Must be "glob" when used with
the by-pattern endpoint, or "branching_model" with by-branch-type.
 [glob, branching_model]`, Required: true},
					{Path: `branch_type`, Type: `string`, Desc: `Branching-model branch type (when branch_match_kind=branching_model).
 [production, development, bugfix, release, feature, hotfix]`},
					{Path: `groups`, Type: `string`, Desc: `Groups exempted from the restriction. Only applies to "push" and
"restrict_merges" kinds.
`, IsArray: true, ItemFields: []BodyFieldDef{
						{Path: `owner`, Type: `string`, Desc: `owner`, IsObject: true, ItemFields: []BodyFieldDef{
							{Path: `username`, Type: `string`, Desc: `username`},
						}},
						{Path: `slug`, Type: `string`, Desc: `The group slug.`},
					}},
					{Path: `kind`, Type: `string`, Desc: `The kind of restriction.
 [push, force, delete, restrict_merges, require_tasks_to_be_completed, require_approvals_to_merge, require_default_reviewer_approvals_to_merge, require_no_changes_requested, require_passing_builds_to_merge, require_commits_behind, reset_pullrequest_approvals_on_change, smart_reset_pullrequest_approvals, reset_pullrequest_changes_requested_on_change, require_all_dependencies_merged, enforce_merge_checks, allow_auto_merge_when_builds_pass]`, Required: true},
					{Path: `pattern`, Type: `string`, Desc: `Branch glob pattern (when branch_match_kind=glob).`},
					{Path: `users`, Type: `string`, Desc: `Users exempted from the restriction. Only applies to "push" and
"restrict_merges" kinds.
`, IsArray: true, ItemFields: []BodyFieldDef{
						{Path: `uuid`, Type: `string`, Desc: `The user UUID, surrounded by curly-braces.`},
					}},
					{Path: `value`, Type: `int`, Desc: `Numeric threshold for kinds that require one (e.g.
require_approvals_to_merge, require_passing_builds_to_merge,
require_commits_behind).
`},
				}},
			},
			HasBody:   true,
			Paginated: false,
			DocURL:    `https://developer.atlassian.com/cloud/bitbucket/rest/api-group-project-branch-restrictions-(internal)/#api-https:--bitbucket.org-!api-internal-workspaces-workspace-projects-project-key-branch-restrictions-by-branch-type-branch-type-put`,
		},
		{
			OperationID: `replaceProjectBranchRestrictionsByPattern`,
			Method:      `PUT`,
			Path:        `https://bitbucket.org/!api/internal/workspaces/{workspace}/projects/{project_key}/branch-restrictions/by-pattern/{pattern}`,
			Summary:     `Replace project branch restrictions matched by glob pattern`,
			Description: `Replaces the full set of project-level branch restriction rules that
match the given branch glob pattern. The "branch_match_kind" of every
rule in the request body must be "glob".

This single endpoint covers Create, Update, and Delete:
  * To create or update rules for a pattern, send the full desired
    values list.
  * To delete all rules for a pattern, send {"values": []}.
`,
			Params: []ParamDef{
				{Name: `workspace`, In: `path`, Type: `string`, Required: true},
				{Name: `project_key`, In: `path`, Type: `string`, Required: true},
				{Name: `pattern`, In: `path`, Type: `string`, Required: true},
			},
			BodyFields: []BodyFieldDef{
				{Path: `values`, Type: `string`, Desc: `The full desired list of rules.`, Required: true, IsArray: true, ItemFields: []BodyFieldDef{
					{Path: `branch_match_kind`, Type: `string`, Desc: `How the rule selects branches. Must be "glob" when used with
the by-pattern endpoint, or "branching_model" with by-branch-type.
 [glob, branching_model]`, Required: true},
					{Path: `branch_type`, Type: `string`, Desc: `Branching-model branch type (when branch_match_kind=branching_model).
 [production, development, bugfix, release, feature, hotfix]`},
					{Path: `groups`, Type: `string`, Desc: `Groups exempted from the restriction. Only applies to "push" and
"restrict_merges" kinds.
`, IsArray: true, ItemFields: []BodyFieldDef{
						{Path: `owner`, Type: `string`, Desc: `owner`, IsObject: true, ItemFields: []BodyFieldDef{
							{Path: `username`, Type: `string`, Desc: `username`},
						}},
						{Path: `slug`, Type: `string`, Desc: `The group slug.`},
					}},
					{Path: `kind`, Type: `string`, Desc: `The kind of restriction.
 [push, force, delete, restrict_merges, require_tasks_to_be_completed, require_approvals_to_merge, require_default_reviewer_approvals_to_merge, require_no_changes_requested, require_passing_builds_to_merge, require_commits_behind, reset_pullrequest_approvals_on_change, smart_reset_pullrequest_approvals, reset_pullrequest_changes_requested_on_change, require_all_dependencies_merged, enforce_merge_checks, allow_auto_merge_when_builds_pass]`, Required: true},
					{Path: `pattern`, Type: `string`, Desc: `Branch glob pattern (when branch_match_kind=glob).`},
					{Path: `users`, Type: `string`, Desc: `Users exempted from the restriction. Only applies to "push" and
"restrict_merges" kinds.
`, IsArray: true, ItemFields: []BodyFieldDef{
						{Path: `uuid`, Type: `string`, Desc: `The user UUID, surrounded by curly-braces.`},
					}},
					{Path: `value`, Type: `int`, Desc: `Numeric threshold for kinds that require one (e.g.
require_approvals_to_merge, require_passing_builds_to_merge,
require_commits_behind).
`},
				}},
			},
			ResponseFields: []BodyFieldDef{
				{Path: `values`, Type: `string`, Desc: `The full desired list of rules.`, Required: true, IsArray: true, ItemFields: []BodyFieldDef{
					{Path: `branch_match_kind`, Type: `string`, Desc: `How the rule selects branches. Must be "glob" when used with
the by-pattern endpoint, or "branching_model" with by-branch-type.
 [glob, branching_model]`, Required: true},
					{Path: `branch_type`, Type: `string`, Desc: `Branching-model branch type (when branch_match_kind=branching_model).
 [production, development, bugfix, release, feature, hotfix]`},
					{Path: `groups`, Type: `string`, Desc: `Groups exempted from the restriction. Only applies to "push" and
"restrict_merges" kinds.
`, IsArray: true, ItemFields: []BodyFieldDef{
						{Path: `owner`, Type: `string`, Desc: `owner`, IsObject: true, ItemFields: []BodyFieldDef{
							{Path: `username`, Type: `string`, Desc: `username`},
						}},
						{Path: `slug`, Type: `string`, Desc: `The group slug.`},
					}},
					{Path: `kind`, Type: `string`, Desc: `The kind of restriction.
 [push, force, delete, restrict_merges, require_tasks_to_be_completed, require_approvals_to_merge, require_default_reviewer_approvals_to_merge, require_no_changes_requested, require_passing_builds_to_merge, require_commits_behind, reset_pullrequest_approvals_on_change, smart_reset_pullrequest_approvals, reset_pullrequest_changes_requested_on_change, require_all_dependencies_merged, enforce_merge_checks, allow_auto_merge_when_builds_pass]`, Required: true},
					{Path: `pattern`, Type: `string`, Desc: `Branch glob pattern (when branch_match_kind=glob).`},
					{Path: `users`, Type: `string`, Desc: `Users exempted from the restriction. Only applies to "push" and
"restrict_merges" kinds.
`, IsArray: true, ItemFields: []BodyFieldDef{
						{Path: `uuid`, Type: `string`, Desc: `The user UUID, surrounded by curly-braces.`},
					}},
					{Path: `value`, Type: `int`, Desc: `Numeric threshold for kinds that require one (e.g.
require_approvals_to_merge, require_passing_builds_to_merge,
require_commits_behind).
`},
				}},
			},
			HasBody:   true,
			Paginated: false,
			DocURL:    `https://developer.atlassian.com/cloud/bitbucket/rest/api-group-project-branch-restrictions-(internal)/#api-https:--bitbucket.org-!api-internal-workspaces-workspace-projects-project-key-branch-restrictions-by-pattern-pattern-put`,
		},
		{
			OperationID: `getProjectBranchRestrictionsGroupedByBranch`,
			Method:      `GET`,
			Path:        `https://bitbucket.org/!api/internal/workspaces/{workspace}/projects/{project_key}/branch-restrictions/group-by-branch/`,
			Summary:     `List project branch restrictions grouped by branch`,
			Description: `Returns the project-level branch restriction rules grouped by the
branch they apply to. Use this as the "Read" / "List" operation when
managing project-level branch restrictions.
`,
			Params: []ParamDef{
				{Name: `workspace`, In: `path`, Type: `string`, Required: true},
				{Name: `project_key`, In: `path`, Type: `string`, Required: true},
			},
			BodyFields:     []BodyFieldDef{},
			ResponseFields: []BodyFieldDef{},
			HasBody:        false,
			Paginated:      false,
			DocURL:         `https://developer.atlassian.com/cloud/bitbucket/rest/api-group-project-branch-restrictions-(internal)/#api-https:--bitbucket.org-!api-internal-workspaces-workspace-projects-project-key-branch-restrictions-group-by-branch--get`,
		},
	},
}
